### ISSUE TITLE
Can't resolve Resource<List<Repo>> in search_fragment.xml

### ISSUE THREAD

**Issue by AlexxS** [googlesamples/android-architecture-components#1]
https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/res/layout/search_fragment.xml#L30
Error:Execution failed for task ':app:dataBindingProcessLayoutsDebug'.
> org.xml.sax.SAXParseException; systemId: file:/D:/workspace/GithubBrowserSample/app/build/intermediates/data-binding-layout-in/debug/layout/search_fragment.xml; lineNumber: 30; columnNumber: 33; The value of attribute "type" associated with an element type "variable" must not contain the '<' character.

Android Studio 3.0 Canary 1

**Comment by yigit** [comment]
fixed w/ the gradle update.
https://github.com/googlesamples/android-architecture-components/commit/3056565891c1deb908156bba6ced520d34092af4
