### ISSUE TITLE
How can I execute raw query?

### ISSUE THREAD

**Issue by DroidNinja** [googlesamples/android-architecture-components#100]
For example, If I want to execute this:
`REPLACE INTO sqlite_sequence (name, seq) VALUES ('tablename', "1001" )`

It shows compile time error : Error:(35, 10) error: INSERT query type is not supported yet. You can use:UPDATE, SELECT, DELETE

**Comment by JoseAlcerreca** [comment]
just call query on your database, you can't use a DAO. 
https://developer.android.com/reference/android/arch/persistence/room/RoomDatabase.html#query(java.lang.String,%20java.lang.Object%5B%5D)

**Comment by yccheok** [comment]
@JoseAlcerreca We have problem using Room DB to access `sqlite_sequence` table. Do you have any input on this - https://github.com/googlesamples/android-architecture-components/issues/330 ?

Thank you.
