### ISSUE TITLE
Build error when implements DataBindingComponent

### ISSUE THREAD

**Issue by zulu-pham** [googlesamples/android-architecture-components#101]
In Github BrowserSample, 
I have error with class FragmentDataBindingComponent when implements DataBindingComponent like that 

Error:(9, 8) error: FragmentDataBindingComponent is not abstract and does not override abstract method getImageViewBindingInterface() in DataBindingComponent

**Comment by JoseAlcerreca** [comment]
Can't seem to reproduce. Closing for now.

**Comment by ArtworkAD** [comment]
@JoseAlcerreca @zulu-pham the BindingAdapters have to be provided by the class that implements DataBindingComponent. See https://stackoverflow.com/a/38216344/401025
