### ISSUE TITLE
BasicRxJavaSample - Bug when you open the app again and update username

### ISSUE THREAD

**Issue by jotish** [googlesamples/android-architecture-components#104]
Once you enter the username and save it.  Force stop the app and start again. 
Live updation of username doesn't happen as expected. 

Prolly because https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaSample/app/src/main/java/com/example/android/observability/ui/UserViewModel.java#L73 `mUser` is  null even though the last username was loaded here https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaSample/app/src/main/java/com/example/android/observability/ui/UserViewModel.java#L54

**Comment by rahulchaurasia3592** [comment]
@florina-muntenescu Same issue as #112. We can close this issue.

**Comment by florina-muntenescu** [comment]
Fixed.
