### ISSUE TITLE
GithubBrowseSample - Context injection

### ISSUE THREAD

**Issue by sviety** [googlesamples/android-architecture-components#107]
I have a question related to new Dagger2 android components used in GithubBrowseSample. I'm slightly confused how can i inject current Activity context. In this sample, application is build using only one Activity so we are injecting MainActvity.class directly. In case of multiple activities how can i inject Activity context?
For example using constructor injection:

class SomeClass{
  @Inject
  public SomeClass(Activity activity){
  ...
  }
}

**Comment by iammert** [comment]
When you inject into your SomeActivity with AndroidInjection.inject(activity), your activity will be added to dagger graph. So you don't need to do anything else. You can use your Activity just like this in your module:
```java
@Module
public class SomeModule{
   @Provides
   public SomeClass provideSomeClass(SomeActivity someActivity){
       return new SomeClass(someActivity);
   }
}
```

**Comment by sviety** [comment]
Thank you @iammert for your response. I'm aware that all of my activities are added to the graph but i'm trying to achive something else. My plan was to add a module like ActivityModule that provides Activity, context and other objects that activity can provide. Using old dagger2 approach i would create an ActivityComponent that have Activity module  with all the neccesary provides methods. After that for all my activties i would create SubComponents of ActivityComponent so the dependencies will be downstreamed.
Reffering to the GithubSample, inside MainActivityModule class i wan't to modify it to add "ActivityModule" to have something like that:

```
@Module
public abstract class MainActivityModule {
    @ContributesAndroidInjector(modules = {ActivityModule.class, FragmentBuildersModule.class})
    abstract MainActivity contributeMainActivity();
}

@Module
public class ActivityModule{

Activity activity;
public ActivityModule(Activity activity)
 this.activity = activity
}

@Provides
Activity provideActitivty(){
return activity;
}
//other provide methods
}
```

The problem is that i don't know how to tell dagger that he should create ActivityModule using MainActivity or any other activity used in my application.

**Comment by iammert** [comment]
Why do you need to provide your activity If it is already on the graph?

**Comment by sviety** [comment]
Reason is very simple. When i'm using architecture with multiple activities i will have a lot of objects that can be used in multiple activities, for exmaple Navigator class used for navigation. A lot of this classes will need Activity context. So for me it is a lot cleaner to create a module that is able to inject Activity context and perform constructor injection on those objects (just like i showed in first post).

**Comment by iammert** [comment]
You can achieve this by using the old way. Create your ActivityComponent which is dependent to AppComponent. Create your ActivityModule which is added to ActivityComponent. Then inject into ActivityComponent in your activity.

**Comment by JoseAlcerreca** [comment]
Looks like this question has been answered and since it's not related to the samples, closing for now.
