### ISSUE TITLE
GithubBrowserSample: demonstrate a way to communicate among ViewModels

### ISSUE THREAD

**Issue by BoD** [googlesamples/android-architecture-components#109]
Hi!

I was looking at a way for one `ViewModel` to access another `ViewModel` and see if there any good practice to do so.
Unfortunately (unless I just didn't find it) this sample doesn't demonstrate a way to do this.

The `ViewModel` guide talks about how you can "Share Data Between Fragments" with a "shared `ViewModel`" but with no sample of how to share data between `ViewModel`s.

**Comment by amrro** [comment]
As I understand That's not the purpose of `ViewModel`. But in the end you could benfit from using `ViewModel` and `LiveData` together. Hence, you can use [`Transformations`](https://developer.android.com/reference/android/arch/lifecycle/Transformations.html) which let you take action based on on change in other `LiveData`; The sample provide some [examples](https://goo.gl/SDw1sh). 

And here in [Docs](https://developer.android.com/topic/libraries/architecture/viewmodel.html#sharing_data_between_fragments), explains how to share `ViewModel`s between fragments.

**Comment by palto-blubek** [comment]
I'm not sure why you're saying this is not the purpose of `ViewModel`.  They allow to separate UI logic from other kinds of logic.  In that sense, you could have one piece in one `ViewModel` that depends on something that is in another one.

For instance: let's say you have a "search query" fragment where the user can fill some criteria.  Then you have a results fragment.  But you also want a "search summary" fragment, that shows some info about the search, including the search query that comes from the "search query" fragment.
To do that, the "search summary" `ViewModel` needs to observe some objects that are managed by the "search query" `ViewModel`.

**Comment by jshvarts** [comment]
I assume in this case your `LifecycleOwner` will be the host `Activity` for those `Fragment`s so the `ViewModel` the Activity creates will be accessible to all of its Fragments.

**Comment by JoseAlcerreca** [comment]
I think the question has been answered, closing for now!

**Comment by Guang1234567** [comment]
[Question] is below:
   
>but with no sample of how to share data between ViewModels.


Nobody has been answer....  ((유∀유|||)) 


@BoD 

My way to share data between ViewModels that in the same activity or fragment:

```
class GroupViewModels extends ViewModel {
   private A_ViewModel aVM;
   private B_ViewModel bVM;

  public GroupViewModels (...) {
    aVM = new A_ViewModel(...);
    bVM = new B_ViewModel(...);
 }
public void onClear() {
    aVM.onClelar();
    bVM.onClear(); 
}

 public Observable<Event>OnNextEvent () {
  return aVM.OnNextEvent();
 
}

```
