### ISSUE TITLE
BasicSample: Correct way to remove comments

### ISSUE THREAD

**Issue by toteto** [googlesamples/android-architecture-components#111]
What would be the correct way to remove comment entries from the DB.  Would excopising the CommentDao as field in [ProductViewModel.java](https://github.com/googlesamples/android-architecture-components/blob/master/BasicSample/app/src/main/java/com/example/android/persistence/viewmodel/ProductViewModel.java#L67), and keeping the ProductViewModel as a field in ProductFragment.java be a good solution?

**Comment by JoseAlcerreca** [comment]
`databaseCreator.getDatabase().commentDao()` is lightweight once the db is created. Don't expose it to the fragment, do the calls in the VM.
