### ISSUE TITLE
BasicRxJavaSample issues : data  can not be refreshed!

### ISSUE THREAD

**Issue by lizixian18** [googlesamples/android-architecture-components#112]
when exit app and open again,click the update button,the data has not changed,still the old data.

**Comment by rahulchaurasia3592** [comment]
@lizixian18 @florina-muntenescu This issue is fixed [here ](https://github.com/rahulchaurasia3592/android-architecture-components/commit/ead9f4175eee360bafc1af996730db81162e5b80). Please merge, if it looks fine.

**Comment by lizixian18** [comment]
OK，Thanks!

**Comment by florina-muntenescu** [comment]
Merged. thank you for the PR!
