### ISSUE TITLE
NavigationController for multiple activities  

### ISSUE THREAD

**Issue by noman87** [googlesamples/android-architecture-components#117]
How can we control if we have multiple activities like Main Activity and User Activity 

@Inject
    public NavigationController(OnBoardingActivity activity) {
        this.containerId = R.id.container;
        this.fragmentManager = activity.getSupportFragmentManager();
    }

**Comment by JoseAlcerreca** [comment]
Doesn't seem to be related to the Architecture Components' samples, closing for now.

**Comment by khatv911** [comment]
@noman87 : what i did was stop using it with dagger. Create a BaseActivity/Fragment and initialize it in onCreate.
