### ISSUE TITLE
Fix README file 

### ISSUE THREAD

**Issue by ivamacio** [googlesamples/android-architecture-components#122]
In the README file, the hyperlink for BasicRxJavaKotlinSample project is pointing out to a wrong url. 

Replace

https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaKotlinSample

to

https://github.com/googlesamples/android-architecture-components/tree/master/BasicRxJavaSampleKotlin

**Comment by florina-muntenescu** [comment]
fixed.
