### ISSUE TITLE
Flowable not updated after inserting data inside a transaction

### ISSUE THREAD

**Issue by tmtron** [googlesamples/android-architecture-components#134]
When we use a Flowable to get an update notification after inserting a new data-base row, works fine.  
But when the insertion is done inside another explicit transaction, the Flowable does not get a notification. 

To illustrate the issue, I've forked the `BasicRxJavaSample` from `android-architecture-components` and added 2 test-methods to [UserDaoTest.java][3]

    @Test
    public void testFlowable() {
        // When subscribing to the emissions of the user
        final TestSubscriber<User> userTestSubscriber = mDatabase.userDao().getUser().test();

        userTestSubscriber.assertValueCount(0);

        // When inserting a new user in the data source
        mDatabase.userDao().insertUser(USER);

        userTestSubscriber.assertValueCount(1);
    }

This works fine. But when I do the same inside of an explicit transaction it does not work:

    @Test
    public void testFlowableInTransaction() {
        // When subscribing to the emissions of the user
        final TestSubscriber<User> userTestSubscriber = mDatabase.userDao().getUser().test();

        userTestSubscriber.assertValueCount(0);

        // When inserting a new user in the data source
        mDatabase.beginTransaction();
        try {
            mDatabase.userDao().insertUser(USER);
            mDatabase.setTransactionSuccessful();

        } finally {
            mDatabase.endTransaction();
        }

        userTestSubscriber.assertValueCount(1);
        // this fails - the userTestSubscriber is still empty!
    }

Note: this example is of course simplified, just to illustrate the issue.

Here's the generated `DaoImpl.insertUser()`:

      public void insertUser(User user) {
        __db.beginTransaction();
        try {
          __insertionAdapterOfUser.insert(user);
          __db.setTransactionSuccessful();
        } finally {
          __db.endTransaction();
        }
      }

We can see that this code uses a transaction and also my test-code uses another transaction.  
According to the [SupportSQLiteDatabase-beginTransaction()][4] docs, nesting transactions should be okay.

Is this maybe a room-bug?

The room version of this project is `1.0.0-alpha3`, but I can also see this problem with version `1.0.0-alpha8` (in another project)

Reference to the [Stackoverflow-question](https://stackoverflow.com/questions/45817010/flowable-not-updated-after-inserting-data-inside-a-transaction)

  [3]: https://github.com/tmtron/android-architecture-components/blob/master/BasicRxJavaSample/app/src/androidTest/java/com/example/android/observability/persistence/UserDaoTest.java#L70
  [4]: https://developer.android.com/reference/android/arch/persistence/db/SupportSQLiteDatabase.html#beginTransaction()

**Comment by JoseAlcerreca** [comment]
Hi tmtron,

Thanks for the very detailed bug report, however these issues are for the samples. Can you please report it using this buganizer component?

https://issuetracker.google.com/issues/new?component=197448&template=878802

Thank you!

**Comment by tmtron** [comment]
oh - sorry, I've mixed up the issue trackers.

For reference: I've filed [#65471397](https://issuetracker.google.com/issues/65471397) on the google issue tracker.

Thanks
