### ISSUE TITLE
LiveData and Adapters

### ISSUE THREAD

**Issue by matejdro** [googlesamples/android-architecture-components#135]
What is the best way to handle adapter updates with data arriving only through LiveData?

With everything in Activity, you could call all methods, such as `adapter.notifyItemAdded()`, but with LiveData you can only submit one type of item, generally whole list to display. That way you can only call `adapter.notifyDataSetChanged()` which documentation states it should be used as last resort.

So is there any better way to do it, or do we just need to call  `adapter.notifyDataSetChanged()` from now on?

**Comment by andhie** [comment]
You can use v7 DiffUtil
https://developer.android.com/reference/android/support/v7/util/DiffUtil.html

**Comment by matejdro** [comment]
Right, but this still throws away the information I have. For example If I add single item to a list in a ViewModel, there is no good way to tell the activity that. I still have to throw away that information, post entire new list and check what happened with DiffUtil.

**Comment by justjanne** [comment]
I’d like to know this as well – I’m working with large (tenthousands of items) datasets, and need to handle their LiveData<List<...>> changing frequently. Just diffing them is a major waste of time. A LiveDataCollection type that can handle collections, and changes within them, would be a major improvement.

**Comment by ChrisCraik** [comment]
You can record the operations on the provider side, and dispatch the notifyItem... messages yourself, alongside the new list, something like: LiveData<Pair<List<>, MyListUpdate>>. You might find something useful in [SortedList](https://developer.android.com/reference/android/support/v7/util/SortedList.html) as well.

Alternately, if you're OK with diffing and just want it to be easier - [ListAdapter](https://developer.android.com/reference/android/support/v7/recyclerview/extensions/ListAdapter.html)
is part of the new [Paging library](https://developer.android.com/topic/libraries/architecture/paging.html) released in Architecture Components last week. It can manage diffing lists for you on a background thread, and can be easily bound to a LiveData<List<...>>

    LiveData<List<Item>> myLiveDataList = ...;

    myLiveDataList.observe(this, list -> adapter.setList(list));

There's also a [PagedListAdapter](https://developer.android.com/reference/android/arch/paging/PagedListAdapter.html), which does the same thing, but also handles updates within a arbitrarily large, lazy-loaded list. For PagedListAdapter specifically, it only diffs the items loaded in memory, and you can just simply call a getter for the item. All of the notifyItem... calls are handled for you.

Both of the adapters use DiffUtil to do the diffing work for you, but they can't be told when there's a specific known update - they'll always do a diff on all the loaded data. Doing that work on a background thread helps though, as does paging - if you have less of each dataset loaded when you're sending a new list, less diffing computation is needed.

**Comment by makk909** [comment]
I don't think any of the solutions mentioned above has related to the Original Question, I want this issue to be reopened as currently I find no way to update a single item in RecyclerView Adapter using LiveData inside ViewModel, we have to set entire list everytime which I don't think a better solution or technique.

**Comment by jkwiecien** [comment]
+1 to reopening, I don't see a way to add, update or remove single item with a combination of `PagedList`, `PagedListAdapter` and `PageKeyedDataSource` (for instance)

Simple case:
Screen  contains list of network fetched items. Element can be swipe-deleted. There is no way of telling any of the mentioned classes that it should just remove a single item from the list.

Same goes for adding or updating.

**Comment by florina-muntenescu** [comment]
Since this is not an issue specifically related to any of the samples, please create an issue on the [official issue tracker](https://issuetracker.google.com/issues?q=componentid=197448%20status:open&s=modified_time:desc) for Architecture Components.

**Comment by yccheok** [comment]
Hey all, I had made an official feature request on this common operation - https://issuetracker.google.com/issues/77363656 :)

**Comment by Skyost** [comment]
Hey everyone, anything new about this issue ?

**Comment by vishnuharidas** [comment]
If you are in control of adding each item to the list, then here is a simple solution to use an accompanying flag to notify the Activity. For example,

    // inside ViewModel
    val animalsList = ArrayList<Animal>()
    val animalsListUpdated: MutableLiveData<Long> = MutableLiveData() // flag
    
    // adding items to the list
    fun updateList(item: Animal){
        animalList.add(item)
        animalListUpdated.value = System.currentTimeMillis() // updating the flag
    }
    
    // inside Activity
    val adapter = Adapter(viewModel.animalsList)
    // observing changes
    viewModel.animalsListUpdated.observe(this, Observer { value -> 
        adapter.notifyDatasetChanged()
    }

**Comment by matejdro** [comment]
I feel like this is the worst solution. You should pass immutable lists through LiveData.

**Comment by vishnuharidas** [comment]
> I feel like this is the worst solution. You should pass immutable lists through LiveData.

Don't worry, a small change will make the LiveData immutable in the above example:

    private val animalsListUpdated_: MutableLiveData<Long> = MutableLiveData()
    val animalsListUpdated: LiveData<Long> get() = animalsListUpdated_

**Comment by matejdro** [comment]
Yes, but list itself is not immutable. You cannot for example update that list freely on the background thread without worying that Android might just be in the middle of the layout phase and drawing that list, causing concurrent modification exceptions.

**Comment by vishnuharidas** [comment]
> Yes, but list itself is not immutable. You cannot for example update that list freely on the background thread without worying that Android might just be in the middle of the layout phase and drawing that list, causing concurrent modification exceptions.

If you are talking about someone outside of the ViewModel updating the list, we can provide an immutable list always. Applying the same logic as above,

    private val _items: MutableList<Animal> = ArrayList()
    val items: List<Animal> get() = _items

Is that what you meant?

**Comment by matejdro** [comment]
No, I'm talking about updating inside viewmodel. This is the proper way to do it:

```kotlin
private var _items: List<Animal> = emptyList()
val items: List<Animal> get() = _items
```

Note that list is not mutable. You can only swap out whole list, but not modify existing one.

**Comment by vishnuharidas** [comment]
So is there any solution for this yet?

**Comment by matejdro** [comment]
It does not look like it. I've just given up and switched to DiffUtils now. Yes, it is a bit less efficient, but it is much more convenient.

**Comment by ivanempire** [comment]
@matejdro Yeah that's fair, although we do handle that manually by using Trello-lifecycle. 😄 Something I did the other day for this, which seemed to work is the following. I'm scanning for BLE devices and displaying them in a list with a custom adapter, so, whenever a new item is discovered, I have:

```
val newlyDiscoveredDevice = MutableLiveData<RxBleDevice>()
```
and I have the observer updating the data:
```
myClass.newlyDiscoveredDevice.observe(this, Observer {
    deviceAdapter.add(it)
})
```
I don't know it something will leak, or if this is a really bad idea but..seems to be OK?

**Comment by matejdro** [comment]
This is really offtopic, but I think it would be easier for you if you would collect devices in the data layer and push `List<RxBleDevice>` through LiveData or Rx or whatever you use.

**Comment by ivanempire** [comment]
Yeah my bad, I didn't mean to throw the thread off-topic, just giving my two cents. I'll check that out! :D

**Comment by abhriyaroy** [comment]
Hey so maybe I am very late, but the best way to implement this seems to be using DiffUtil for a recyclerview.

**Comment by alexgomes09** [comment]
2023 yet there's really no way other than using DiffUtils. :(

**Comment by ivanempire** [comment]
I think at this point you're better off using Kotlin Flows and Flow operators + lazy layouts in Jetpack Compose.
