### ISSUE TITLE
Compilation errors : Interface that extends LifecycleObserver

### ISSUE THREAD

**Issue by HappyDr0id** [googlesamples/android-architecture-components#151]
I have a MVP architecture with an IView interface that extends the LifecycleObserver. Because of that, I get compilation errors for each used lifecycle annotation, like this one : 

> error: 1st argument of a callback method must be a LifecycleOwner which represents the source of the event

I systematically get errors when using kapt, but not with annotationProcessor (even though I have to clean the project between each compilation, which is kind of annoying too).
It seems that using an interface that extends LifecycleObserver is the cause of the problem ; if I implement LifecycleObserver with an abstract class or a class, I do not get errors anymore.

Is someone else experiencing the same issue ?

Thanks in advance !

**Comment by HappyDr0id** [comment]
Here is the issue I posted about the same subject on the Jetbrains tracker : https://youtrack.jetbrains.com/issue/KT-20232#comment=27-2484626. Someone from the team answered me that the problem could come from the Android architecture components library.

**Comment by mesnault** [comment]
I'm experiencing the same problem.

**Comment by JoseAlcerreca** [comment]
Sorry, this is the tracker for issues with the samples. Closing!
