### ISSUE TITLE
is this way is ok(it is just a sample),am i doing something wrong??

### ISSUE THREAD

**Issue by prabinshrestha** [googlesamples/android-architecture-components#152]
public class ExampleActivity extends LifecycleActivity {

// click the button 
//notice here i make the livedata instance inside the method and pass it to model
// instead of getting return LiveData from model, i passed it as argument and later will be used 
//by repository 

    void onClickButton() {
        MutableLiveData<Response<Data>> liveData = new MutableLiveData<>();
        liveData.observe(this, new Observer<Response<Data>>() {
            @Override
            public void onChanged(@Nullable Response<Data> dataResponse) {
                //update our ui... with dataResponse

                switch (dataResponse.status)

                case Loading: {
                    //show dialog progress
                }

                case LoadinFinished: {
                 //dismiss dialog progress
                }

                case SUCCESS: {
                    //upadate ui with data
                    //dataResponse.somedata;

                }

                case ERROR: {
                //deal with error
                }

            }
        });

//here i pass it the live data in a method....

exampleActivityModel. getSomeDataFromRepository( liveData);

    }

}

public class ExampleActivityModel extends AndroidViewModel {

    DataRepository dataRepository;

    public ExampleActivityModel(Application application) {
        super(application);
    }

//just throw it to repository

    public void getSomeDataFromRepository(MutableLiveData<Response<Data>> liveData) {
        dataRepository.getData(liveData);
    }

}

public class DataRepository {

// the repository will then do some manipulation with livedata

    public void getData(MutableLiveData<Response<Data>> liveData) {
        //network call for example retrofit
        liveData.setValue(new Response<Data>(Status.Loading));

        retrofit.onsucess() {
            liveData.setValue(new Response<Data>(Status.LoadingFinished));

        }
        retrofit.onError() {
            liveData.setValue(new Response<Data>(Status.Error));
        }

    }

}

public class Data {

    String someData;

    String getSomeValue() {
        return someData;
    }
}

**Comment by JoseAlcerreca** [comment]
It's hard to read, can you please change the title to a summary of the problem and reformat? Closing for now.

**Comment by prabinshrestha** [comment]
Can you check again, i have formatted the code.I hope you will understand
it now.

I just wanna know if it is feasible solution to pass livedata in viewmodel
method or do we have to make global variable for live data everytime.

Just wanna know some information and best way possible.
