### ISSUE TITLE
RxJava only works with Queries?

### ISSUE THREAD

**Issue by wengelef** [googlesamples/android-architecture-components#162]
Is it not possible (out of the box) to use RxJava for insert/update?
Like return a `Flowable<Long>` or `Flowable<Any>` instead.

**Comment by mynote** [comment]
Since you use LiveData to listen for changes, you may use RxJava to listen for changed by observing Select * ... 

The return value of update/delete  are the row/inserted id which isnt used to observe for changes. If you really want to get this value in a different Thread use Flowable.fromCallable() Flowable.create() or Flowable.just().

I think this may be the reason for that.

**Comment by florina-muntenescu** [comment]
There is already a bug raised for this on the official bug tracker, [here](https://issuetracker.google.com/63613835).

**Comment by birender-s** [comment]
i am also looking forward for this feature availability

**Comment by XtreeIvI** [comment]
1+

**Comment by proninyaroslav** [comment]
@florina-muntenescu What about LiveData support?

**Comment by involve-it** [comment]
> RxJava is supported for insert/update/delete since Room 2.1.0-alpha01

Could you please give us a hint on how to use it with room's insert/update/delete?

**Comment by proninyaroslav** [comment]
@involve-it
For example:
```Java
@Insert
Single<List<Long>> add(Foo... f) /* Id of added rows */

@Delete
Single<Integer> delete(Foo... f) /* Num of deleted rows */

@Update
Single<Integer> update(Foo... f) /* Num of updated rows */
```

**Comment by involve-it** [comment]
> @involve-it
> For example:
> 
> ```java
> @Insert
> Single<List<Long>> add(Foo... f); /* Id of added rows */
> 
> @Delete
> Single<Integer> delete(Foo... f); /* Num of deleted rows */
> 
> @Update
> Single<Integer> update(Foo... f); /* Num of updated rows */
> ```
> 
> And how to observe it:
> 
> ```java
> Disposable d = db.fooDao().add(new Foo("bar"))
> .subscribeOn(Schedulers.io())
> .observeOn(AndroidSchedulers.mainThread())
> .subscribe(ids -> /* Do stuff */);
> disposables.add(d);
> ```

Awesome, thanks!
