### ISSUE TITLE
AS 3.0 Beta 6 bug using Gradle 3.0.0-beta6 (1.0.0-beta1)

### ISSUE THREAD

**Issue by mynote** [googlesamples/android-architecture-components#172]
Using AS 3.0 Beta 6 and gradle 3.0.0-beta6 throws a warning about arch components using version **1.0.0-beta1**

It recommends using a "newer" version 1.0.0-alpha9-1 which is a false warning.

**Comment by andre-artus** [comment]
I get this as well.

**Comment by florina-muntenescu** [comment]
This has already been reported on the official issue tracker [here](https://issuetracker.google.com/66794173).
