### ISSUE TITLE
Why don't `GithubApp` extend `DaggerApplication`?

### ISSUE THREAD

**Issue by mathewhany** [googlesamples/android-architecture-components#18]
Isn't it easier to make `GithubApp` extend `DaggerApplication` and `AppComponent` extend `AndroidInjector<GithubApp>`? Or is there a purpose for not doing that?

**Comment by yigit** [comment]
Yes, it is on purpose (same for activities and fragments). Using base classes is tricky since you can only extend one so this sample uses other integration points to avoid limiting apps.
Same goes for LifecycleActivity/LifecycleFragment. 
For instance, [search fragment][1]
