### ISSUE TITLE
Room Migrations - Schema file date changes on project rebuild

### ISSUE THREAD

**Issue by andre-artus** [googlesamples/android-architecture-components#191]
I'm using the following setting in my `app/build.gradle` 
``` gradle
android {
// . . .
    defaultConfig {
        // . . .
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
    }
// . . .
}
```

I've noticed that the schema file's date changes whenever I do a rebuild despite there being no changes to either the Entities or the Dao (or really any code file). Is this by design? Can I disable it? I tend to occasionally trigger a build (usually right before going for a coffee), so I would like for it not to do that.

This is of course more of an annoyance than a showstopper as with the file contents not actually changing it does not affect source control.

**Comment by yigit** [comment]
we don't really export a date in the schema file. The last edited timestamp of the file will change but gradle should ignore it since it uses content hashes to identify changes.

On another note, it is better to report these on the issuetracker with the problem it is causing so that we can track the issue.

**Comment by andre-artus** [comment]
Sorry to cause inconvenience, when you search for "android architecture components issue tracker" on Google then this page comes up first. I've since reading your reply found (through a more convoluted route) that the actual issue tracker lies here
Android Public Tracker > App Development > Architecture Components, I'll repost my issue there.

**Comment by florina-muntenescu** [comment]
@andre-artus You can also find the link in the README.md of this repository, in the "Issues" section: https://github.com/googlesamples/android-architecture-components

**Comment by andre-artus** [comment]
Thanks @florina-muntenescu , should have looked there first, just so used to initiating a search whenever I need to find something. Honestly I have not looked at the README.md beyond glancing over it months ago. 

In any case I've reported it on the Architecture Components Issue Tracker, with an expansion on why it is an issue (which I could have probably been clearer on here).

Also I want to thank you guys, I'm enjoying working with the AAC.
