### ISSUE TITLE
Compilation error on BasicRxJavaSample when trying to add new entity class

### ISSUE THREAD

**Issue by biswanathgit** [googlesamples/android-architecture-components#192]
Error:(14, 8) error: Entities and Pojos must have a usable public constructor. You can have an empty constructor or a constructor whose parameters match the fields (by name and type).Tried the following constructors but they failed to match:= Department(java.lang.String,java.lang.String) : [id : null, dep : null]
Error:(16, 20) error: Cannot find setter for field.
Error:(18, 20)error: Cannot find setter for field.

Description :  I am trying to add another entity class with the same implementation of User entity . But got above errors.

**Comment by yigit** [comment]
please provide the class that you've tried to add.
Also, if you think it is a bug, it is better to report in issuetracker.google.com
