### ISSUE TITLE
Paging : Not sure how to convert a Cursor to this method's return type

### ISSUE THREAD

**Issue by burhanrashid52** [googlesamples/android-architecture-components#198]
I am getting error for LivePagedListProvider Return type while compiling 

Error:(22, 58) error: Not sure how to convert a Cursor to this method's return type

```
@Dao
public interface UserDao {
    @Query("SELECT * FROM user")
    public abstract LivePagedListProvider<Integer, User> getAllPagination();
}
```

How to resolve this issue i have setup everything correct as per the sample documentation

**Comment by n0lik** [comment]
Hello! Could you share all code?

**Comment by burhanrashid52** [comment]
https://stackoverflow.com/questions/46668605/paging-compile-issue-not-sure-how-to-convert-a-cursor-to-this-methods-return
As i have asked this question with detail code
@n0lik

**Comment by burhanrashid52** [comment]
I resolved the issue by updating the libraries to the latest version

```
compile 'android.arch.persistence.room:runtime:1.0.0-beta2'
    annotationProcessor 'android.arch.persistence.room:compiler:1.0.0-beta2'
    compile 'android.arch.paging:runtime:1.0.0-alpha3'

    compile 'android.arch.lifecycle:runtime:1.0.0-beta2'
    compile 'android.arch.lifecycle:extensions:1.0.0-beta2'
    annotationProcessor 'android.arch.lifecycle:compiler:1.0.0-beta2'
```

**Comment by krunalshah-insigmainc** [comment]
I am using androidx room lib and it is up to date. Still I am facing same issue.

**Comment by dlam** [comment]
This is an issue from 2017

If you're using Paging 2.1, you should instead use `DataSource.Factory`, which room knows how to return, and pass that to a `LivePagedListBuilder`

See:
https://github.com/googlesamples/android-architecture-components/blob/17c315a050745c61ae8e79000bc0251305bd148b/PagingSample/app/src/main/java/paging/android/example/com/pagingsample/CheeseDao.kt#L35

And its usage:
https://github.com/googlesamples/android-architecture-components/blob/48974fce8c1bc1ff8542b44ae1761a2d9a80d8c0/PagingSample/app/src/main/java/paging/android/example/com/pagingsample/CheeseViewModel.kt#L34

Note that `toLiveData` is an extension method which simply calls into https://developer.android.com/reference/android/arch/paging/LivePagedListBuilder

**Comment by liodali** [comment]
i have the same problem with paging 3

**Comment by shikoko** [comment]
@liodali what room version are you using? Try using the latest one at the moment - `2.3.0-alpha02`

**Comment by liodali** [comment]
i'm using version 2.2.5 for room and paging 3 alpha
the build failed message : Not sure how to convert a Cursor to this method's return type androidx.paging.PagingSource

**Comment by dlam** [comment]
PagingSource was added in Room 2.3.0-alpha01+

**Comment by chamellion** [comment]
Check whether you are not trying to insert a list of objects into your DB, you will need to either embed, use a foreign key or declare the relationship in another table

**Comment by lesniakania** [comment]
This is a full list of dependencies that helped me:

```
def roomVersion = "2.3.0-alpha03"
    implementation "androidx.room:room-runtime:$roomVersion"
    kapt "androidx.room:room-runtime:$roomVersion"
    kapt "androidx.room:room-compiler:$roomVersion"
```

especially the part with

```
kapt "androidx.room:room-compiler:$roomVersion"
```
