### ISSUE TITLE
Failed to complete Gradle execution

### ISSUE THREAD

**Issue by wafer-li** [googlesamples/android-architecture-components#2]
Error:Failed to complete Gradle execution.

Cause:
The version of Gradle you are using (3.4.1) does not support the forTasks() method on 
BuildActionExecuter. Support for this is available in Gradle 3.5 and all later versions.

Step to Reproduce:
Click the green arrow to build and run the APP

**Comment by wafer-li** [comment]
Using Android Studio 3.0 canary 1

**Comment by Aeolus-dan** [comment]
I have these errors：
     Failed to resolve: android.arch.lifecycle:extensions:1.0.0-alpha1
     Failed to resolve: annotationProcessor
     Failed to resolve: android.arch.persistence.room:runtime:1.0.0-alpha1

because i can't connect https://maven.google.com ? ?

**Comment by ouyangzn** [comment]
@Aeolus-dan Maybe, you should try again.

**Comment by 8888444422** [comment]
j9000905@gmail.com

**Comment by shanuka** [comment]
if your using Android Studio 3.0 canary 1 please update gradle as follows
~~~
-        classpath 'com.android.tools.build:gradle:2.3.1'
+        classpath 'com.android.tools.build:gradle:3.0.0-alpha1'
~~~

and gradle wrapper as follows
~~~
-distributionUrl=https\://services.gradle.org/distributions/gradle-3.4.1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-milestone-1-all.zip
~~~

**Comment by wafer-li** [comment]
@shanuka 

OK, update the gradle will end up with the data binding error, which may relate to #1

**Comment by shanuka** [comment]
@wafer-li 
revert what you did in above comment and 
type following command

~~~
./gradlew installDebug
~~~

**Comment by florina-muntenescu** [comment]
Install issue fixed by this [PR](https://github.com/googlesamples/android-architecture-components/pull/7).

**Comment by chenycu** [comment]
Still compile failed, to be crazy, help me

> Failed to resolve: annotationProcessor Open File

**Comment by shanuka** [comment]
@chenyc
which is android studio version you may using?

**Comment by chenycu** [comment]
@shanuka
Android Studio 3.0 canary 1
I did as you said above, but still can not solve

**Comment by wafer-li** [comment]
@chenycu
It seems you need to cross the Great Fire Wall

**Comment by ouyangzn** [comment]
@chenycu
You need VPN

**Comment by chenycu** [comment]
I have used the VPN, you can normally visit google.
Sometimes reported the following   @@mistakes:

Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:generateDebugAndroidTestSources]
Error:Execution failed for task ':app:mockableAndroidJar'.
> Could not initialize class com.android.ide.common.util.ReadWriteProcessLock
Information:BUILD FAILED in 1s
Information:1 error
Information:0 warnings
Information:See complete output in console


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mockableAndroidJar'.
> Could not initialize class com.android.ide.common.util.ReadWriteProcessLock

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
14 actionable tasks: 5 executed, 9 avoided (64%)

@shanuka    @wafer-li  @ouyangzn

**Comment by dazhaoDai** [comment]
open “gradle-wrapper.properties”，change：

distributionUrl=https\://services.gradle.org/distributions/gradle-4.0-milestone-1-all.zip
