### ISSUE TITLE
[Question]Where in such architecture services should be placed?

### ISSUE THREAD

**Issue by wnasilow** [googlesamples/android-architecture-components#20]
Should ViewModels communicate directly with services, or via repository?
The service is responsible for media streaming, and relies on external library.

**Comment by JoseAlcerreca** [comment]
Closing as it's out of the scope of the arch components, I recommend stackoverflow for these questions.

**Comment by iammert** [comment]
@JoseAlcerreca Where does the `ServiceConnection` belongs to? `ViewModel` or `Activity`/`Fragment`? What is the best place to call `bindService()`? UI components or `AndroidViewModel`?  I think we should create a sample which is showing that how we can use `Service` with `ViewModel`. Or can we combine?

**Comment by vicobz** [comment]
> Where does the `ServiceConnection` belongs to? `ViewModel` or `Activity`/`Fragment`? What is the best place to call `bindService()`? UI components or `AndroidViewModel`? I think we should create a sample which is showing that how we can use `Service` with `ViewModel`. Or can we?

Hi @iammert ! Do you have any news or update on this topic? :)

**Comment by dglozano** [comment]
@iammert I would be interested too. [I wrote a question in stackoverflow as well.](https://stackoverflow.com/questions/53382320/where-to-place-android-boundservice-in-the-new-recommended-mvvm-architecture)

**Comment by mkriteja** [comment]
Any guidance / solutions to this @iammert @RicoSchueppel @dglozano

**Comment by rajattri** [comment]
I am also stuck over this problem (https://stackoverflow.com/questions/60692553/creating-an-interface-between-websocketservice-and-viewmodel)

I need to bind my WebSocketService to viewmodel, but stuck at creating the interface.

Any help would be appreciated.
