### ISSUE TITLE
Bug : ViewmodelProvider returns different instance of VM for Activity and Fragment

### ISSUE THREAD

**Issue by savant-martins** [googlesamples/android-architecture-components#202]
Support lib v7:26.1.0
Architecture components beta2 

VM created in Activity using 
stockcheckViewModel = ViewModelProviders.of(this).get(StockcheckViewModel.class);

And in fragment (from onCreateView)
stockcheckViewModel = ViewModelProviders.of(getActivity()).get(StockcheckViewModel.class);

Fragment created in activity using getSupportFragmentManager()

Stepping through the code it seems that the ViewModelProvider creates a different stores instance for the Activity and Fragment

https://stackoverflow.com/questions/46574672/lifecycle-viewmodel-not-shared-between-activity-and-fragments

**Comment by yigit** [comment]
in your samples, i don't see where `initViewModel` is called. If you are calling it before `onCreate`, you might end up in this situation.

**Comment by ianhanniballake** [comment]
Please file issues with ViewModel on the [issue tracker](https://issuetracker.google.com/issues/new?component=413132) with a sample project that reproduces your issue.
