### ISSUE TITLE
not able to run any of these project in android studio

### ISSUE THREAD

**Issue by umarpazir11** [googlesamples/android-architecture-components#213]

**Comment by ivotai** [comment]
that's your problem, more detail please.

**Comment by Artenes** [comment]
@umarpazir11 this might help you: https://github.com/googlesamples/android-architecture-components/issues/219

@ivotai this is a duplicate.

**Comment by edwardotis** [comment]
This project won't work if you pull the entire repo down. Here's the way to get each sample in Android Studio 3.2.1

Start Android Studio
From Splash Screen, click on "Import sample"
Choose a sample provided by this repository (in my example: "Architecture Components Paging")
Finish the wizard (set a location, etc.)

**Comment by ianhanniballake** [comment]
You can also download the whole project, then open the individual projects.
