### ISSUE TITLE
BasicRxJavaSampleKotlin UserActivity should be an AppCompatActivity

### ISSUE THREAD

**Issue by tensory** [googlesamples/android-architecture-components#226]
`UserActivity` inherits from deprecated `LifecycleActivity`.
It should inherit from `AppCompatActivity`.

**Comment by florina-muntenescu** [comment]
Feel free to create a PR for this.

**Comment by tensory** [comment]
Opened https://github.com/googlesamples/android-architecture-components/pull/227. Thanks, @florina-muntenescu !

**Comment by florina-muntenescu** [comment]
Merged! thanks
