### ISSUE TITLE
MVP TODO project link missing

### ISSUE THREAD

**Issue by KerryHeroVitamin** [googlesamples/android-architecture-components#230]
Hi,

I was trying to see the code for the project "Architecture Blueprints - todo-mvp-room", but it leads to a 404 page not found error. Hope you can fix it 😃.

**Comment by jimandreas** [comment]
@KerryHeroVitamin - todo-mvp using Room: Here is a link - 

https://github.com/googlesamples/android-architecture/tree/todo-mvp

The repo branch was updated by PR [#450](https://github.com/googlesamples/android-architecture/pull/450) by @JoseAlcerreca recently.

The changes to update todo-mvp to use Room can be seen [here](https://github.com/googlesamples/android-architecture/commit/30f7c5a16bb0854e003530e81403e922e745d311).

**Comment by florina-muntenescu** [comment]
Readme updated. Thanks @KerryHeroVitamin!
