### ISSUE TITLE
ViewModel and Service

### ISSUE THREAD

**Issue by MotiBartov** [googlesamples/android-architecture-components#236]
Hi,

I have a question regarding the recommended architecture to share data from ViewModel to a Service and vice versa. 

In my app, an Activity that instantiate a ViewModel and also binds to a Service.
The Service manages a few WebSockets which sends and receives network messages in the background.
 
The communication between the Activity to the Service is done through callback interface and also public methods in the Service which the Activity calls. 

By this, the activity can send and receive messages from the WebSockets and then updates the ViewModel with the messages from the sockets, or from the ViewModel to the sockets. 

What is the best way to send and receive messages between a ViewModel and a Service? 
Should it go through the Activity ?

Thanks, 
Moti.

**Comment by florina-muntenescu** [comment]
Your Service data should go through a repository.
Check out the [guide to app architecture](https://developer.android.com/topic/libraries/architecture/guide.html) for details.

**Comment by alishir** [comment]
@florina-muntenescu I have the same question, would you please describe how to inject repository to the service? I think service should insert data to the repository and repository inform viewmodel about data change, am I right?
