### ISSUE TITLE
get only changes in onChange method

### ISSUE THREAD

**Issue by mchenani** [googlesamples/android-architecture-components#240]
Hi there,
Thanks for ArchComponents, I need to get only the changes in LiveData.OnChange method. Are there any practices? We moved from cursorLoader to room and live data and paginLibrary, but this onChange mechanism is painful.

**Comment by florina-muntenescu** [comment]
If you just want the difference between what was emitted the previous time and the current time, you can create your own `MutableLiveData` that caches the last result and computes the difference.
