### ISSUE TITLE
PagingWithNetworkSample - failed

### ISSUE THREAD

**Issue by vladanSD** [googlesamples/android-architecture-components#245]
Hello guys, 

I would like to report ANR on your new sample. 
If you use DB + NETWORK case, and use pull to refresh app crashes.

12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349] Throwing new exception 'length=246; index=1434' with unexpected pending exception: java.lang.ArrayIndexOutOfBoundsException: length=246; index=1434
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.arch.lifecycle.LiveData com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository.refresh(java.lang.String) (DbRedditPostRepository.kt:75)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.arch.lifecycle.LiveData com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository.access$refresh(com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository, java.lang.String) (DbRedditPostRepository.kt:39)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.arch.lifecycle.LiveData com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository$postsOfSubreddit$refreshState$1.apply(kotlin.Unit) (DbRedditPostRepository.kt:122)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at java.lang.Object com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository$postsOfSubreddit$refreshState$1.apply(java.lang.Object) (DbRedditPostRepository.kt:39)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.arch.lifecycle.Transformations$2.onChanged(java.lang.Object) (Transformations.java:133)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.arch.lifecycle.MediatorLiveData$Source.onChanged(java.lang.Object) (MediatorLiveData.java:152)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.arch.lifecycle.LiveData.considerNotify(android.arch.lifecycle.LiveData$LifecycleBoundObserver) (LiveData.java:131)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.arch.lifecycle.LiveData.dispatchingValue(android.arch.lifecycle.LiveData$LifecycleBoundObserver) (LiveData.java:148)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.arch.lifecycle.LiveData.setValue(java.lang.Object) (LiveData.java:294)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.arch.lifecycle.MutableLiveData.setValue(java.lang.Object) (MutableLiveData.java:33)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository$postsOfSubreddit$2.invoke() (DbRedditPostRepository.kt:132)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at java.lang.Object com.android.example.paging.pagingwithnetwork.reddit.repository.inDb.DbRedditPostRepository$postsOfSubreddit$2.invoke() (DbRedditPostRepository.kt:39)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void com.android.example.paging.pagingwithnetwork.reddit.ui.SubRedditViewModel.refresh() (SubRedditViewModel.kt:38)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void com.android.example.paging.pagingwithnetwork.reddit.ui.RedditActivity$initSwipeToRefresh$2.onRefresh() (RedditActivity.kt:100)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.support.v4.widget.SwipeRefreshLayout$1.onAnimationEnd(android.view.animation.Animation) (SwipeRefreshLayout.java:187)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.support.v4.widget.CircleImageView.onAnimationEnd() (CircleImageView.java:106)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.finishAnimatingView(android.view.View, android.view.animation.Animation) (ViewGroup.java:6125)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16240)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.View.draw(android.graphics.Canvas) (View.java:16299)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15293)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16066)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15288)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16066)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15288)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16066)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15288)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16066)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15288)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16066)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15288)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.View.draw(android.graphics.Canvas, android.view.ViewGroup, long) (View.java:16066)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at boolean android.view.ViewGroup.drawChild(android.graphics.Canvas, android.view.View, long) (ViewGroup.java:3621)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas) (ViewGroup.java:3411)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.View.draw(android.graphics.Canvas) (View.java:16299)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void com.android.internal.policy.PhoneWindow$DecorView.draw(android.graphics.Canvas) (PhoneWindow.java:2740)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at android.view.RenderNode android.view.View.updateDisplayListIfDirty() (View.java:15293)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ThreadedRenderer.updateViewTreeDisplayList(android.view.View) (ThreadedRenderer.java:295)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ThreadedRenderer.updateRootDisplayList(android.view.View, android.view.HardwareRenderer$HardwareDrawCallbacks) (ThreadedRenderer.java:301)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ThreadedRenderer.draw(android.view.View, android.view.View$AttachInfo, android.view.HardwareRenderer$HardwareDrawCallbacks) (ThreadedRenderer.java:336)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewRootImpl.draw(boolean) (ViewRootImpl.java:2787)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewRootImpl.performDraw() (ViewRootImpl.java:2591)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewRootImpl.performTraversals() (ViewRootImpl.java:2191)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewRootImpl.doTraversal() (ViewRootImpl.java:1198)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.ViewRootImpl$TraversalRunnable.run() (ViewRootImpl.java:6268)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.Choreographer$CallbackRecord.run(long) (Choreographer.java:873)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.Choreographer.doCallbacks(int, long) (Choreographer.java:676)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.Choreographer.doFrame(long, int) (Choreographer.java:606)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.view.Choreographer$FrameDisplayEventReceiver.run() (Choreographer.java:859)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:739)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.os.Looper.loop() (Looper.java:168)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5885)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:797)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:687)
12-08 12:36:37.183 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/thread.cc:1349] 
12-08 12:36:37.293 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
12-08 12:36:37.293 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/runtime.cc:366] Runtime aborting --- recursively, so no thread-specific detail!
12-08 12:36:37.293 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/runtime.cc:366] 
12-08 12:36:37.293 31074-31074/com.android.example.paging.pagingwithnetwork A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31074 (gingwithnetwork)

**Comment by yigit** [comment]
that looks like a weird state, 
```
2-08 12:36:37.293 31074-31074/com.android.example.paging.pagingwithnetwork A/art: art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
```

I also cannot reproduce this issue, can you add more details on how this happened?

thanks.

**Comment by vladanSD** [comment]
I haven't made any code changes. 
I have downloaded code samples again and the issue persist.
Just run app, click on first button "DB+NETWORK", search works perfect, but when you try to pull to refresh already loaded list I get that error. 
I tried 2 phones and 2 different laptops and crash is still there.

**Comment by yigit** [comment]
that is so weird :/ i cannot reproduce.

here is a video of what i'm trying.

[paging.mp4.zip](https://github.com/googlesamples/android-architecture-components/files/1548804/paging.mp4.zip)

**Comment by JoseAlcerreca** [comment]
Can't reproduce either. 

I cloned the repo from scratch.

What AS are you using to run it?

**Comment by vladanSD** [comment]
@yigit yes, thats the case I'm getting error :(
@JoseAlcerreca latest stable version
Btw I've tried on emulator, its working. But when I try on device it fails again.

**Comment by vladanSD** [comment]
Ok guys, I fixed it by disabling instant run in AS, any suggestion how to avoid disabling it? :D

**Comment by vladanSD** [comment]
![image](https://user-images.githubusercontent.com/15196775/33855924-d1329406-dec6-11e7-983d-32932dcd0986.png)

check this out, its on 3.1 canary 5.. still getting error + these warnings
I'll report it on issuetracker if you don't have any new idea
