### ISSUE TITLE
Docs: Wrong paging library version

### ISSUE THREAD

**Issue by marioavs** [googlesamples/android-architecture-components#246]
The samples are applying versions.paging = "1.0.0-alpha4", but the document Adding Components to your Project (https://developer.android.com/topic/libraries/architecture/adding-components.html) are making reference to android.arch.paging:runtime:1.0.0-alpha3

DataSource.Factory is missing when using the version from the documentation

**Comment by yigit** [comment]
will fix today, thanks!
