### ISSUE TITLE
Can't use maven.google.com from China

### ISSUE THREAD

**Issue by gaidie** [googlesamples/android-architecture-components#25]
compile "android.arch.lifecycle:runtime:1.0.0-alpha1"
compile "android.arch.lifecycle:extensions:1.0.0-alpha1"
annotationProcessor "android.arch.lifecycle:compiler:1.0.0-alpha1"

in China, all above can not build success.can you apply some realse jar for us

**Comment by JoseAlcerreca** [comment]
@yigit is there something we can do about this?

**Comment by wafer-li** [comment]
@JoseAlcerreca 
Nowadays, we can access `dl.google.com` to download the Android SDK, while long time ago, we must use VPN or something else to achieve that.

Could your guys do the same thing with `maven.google.com` again?

**Comment by gaidie** [comment]
@wafer-li 
thank you! I chang the url maven.google.com to https://dl.google.com/dl/android/maven2/
and then i build success!

**Comment by xiaobailong24** [comment]
Optional edit Windows HOSTS(C:\Windows\System32\drivers\etc)
add below line:
```
216.58.217.206 maven.google.com
```
That works for me!

**Comment by XingdongYu** [comment]
it doesn't work for me :(

**Comment by snowdream** [comment]
maven { url "https://dl.google.com/dl/android/maven2/" }
