### ISSUE TITLE
Could not read script '.../versions.gradle' as it does not exist

### ISSUE THREAD

**Issue by bytebeats** [googlesamples/android-architecture-components#259]
`Android Studio 3.0.1`

`Import an Android code sample: `

Search `Room & Rx Java` and then click `Next`

After downloaded, project `RoomRxJava` can't be open.

Gradle says: `Could not read script '.../versions.gradle' as it does not exist`

Yes, No file `versions.gradle` found through the whole project.

So, What can I do now?

**Comment by gepardy** [comment]
It is placed in [android-architecture-components](https://github.com/googlesamples/android-architecture-components), so copy it and place in the folder above the RoomRxJava

**Comment by florina-muntenescu** [comment]
The file is in the [root of the repo](https://github.com/googlesamples/android-architecture-components/blob/master/versions.gradle).

**Comment by anitawoodruff** [comment]
That's a great workaround, but surely it's a bug in the sample if people have to manually add the file?

**Comment by florina-muntenescu** [comment]
Without a common versions.gradle file, we would need to manually update the build.gradle file for every project, whenever an increase in version number for a library is wanted. Like this, only one file is modified and all samples get to be up to date.

**Comment by anitawoodruff** [comment]
Hmm then maybe android studio needs to be smarter about importing samples?

**Comment by anitawoodruff** [comment]
Or.. you could accept the duplication and have a script for updating the version.gradle in all subrepos at once - how often does this happen?

I think the benefit of having the samples being standalone outweighs the downside of having to update multiple files.
