### ISSUE TITLE
items dont get appended from PositionalDataSource in Paging Library

### ISSUE THREAD

**Issue by nishant304** [googlesamples/android-architecture-components#260]
Thanks for this awesome library. 
May be I am doing something wrong in the implementation, 

But after hours of debugging, seems like result for PositionalDataSource in 
loadRange gets ignored in PagedList.

Here is what I found :

1. For appending more items, dispatchLoadRange is called which creates a callback 
    with result type PageResult.TILE

2. In ContinousPagedList there is no handling for tyled result type. 

```
[if (resultType == PageResult.INIT) {

                mStorage.init(pageResult.leadingNulls, page, pageResult.trailingNulls,
                        pageResult.positionOffset, ContiguousPagedList.this);
                mLastLoad = pageResult.leadingNulls + pageResult.positionOffset + page.size() / 2;

            } else if (resultType == PageResult.APPEND) {

                mStorage.appendPage(page, ContiguousPagedList.this);

            } else if (resultType == PageResult.PREPEND) {

                mStorage.prependPage(page, ContiguousPagedList.this);

            }
](`url`)
 

```
Also found that, enabling Placeholders, the problem goes away, as TiledPagedList becomes the data holder instead of ContinousPagedList.

**Comment by nishant304** [comment]
A workaround can be to  make isContiguous in DataSource to return false.

In my humble opinion, this should be mentioned in docs.

**Comment by nishant304** [comment]
Yeah. Spot on.

**Comment by alexsullivan114** [comment]
Looks like this one is already logged and is scheduled to be fixed in the next release. Hopefully that's soon!

https://issuetracker.google.com/issues/70573345

**Comment by nishant304** [comment]
Issue Fixed Now

**Comment by Turskyi** [comment]
Not fixed
