### ISSUE TITLE
Confused about Entity or Dto

### ISSUE THREAD

**Issue by prabinshrestha** [googlesamples/android-architecture-components#267]
*Should we consider using separate class for entity and other separate class as dto?
*What is the best practise?
*If used, how can we use in the best way,and also do we need any mapper for it, any great example for android available?

**Comment by iammert** [comment]
You can create your model/entity classes for every single layer. You don't have to do it, but it will be more flexible and easy to maintain in this way. While your data is streaming from back-layer(Cache, DB, remote) to front-layer(ViewModel), you can map your data(Vice versa).

This is from @yigit 

> It is usually a good practice to separate your data transfer objects from your entities.
> So when you pull the data, you have to normalize it into your entities. When pulling the data, you can use the @Relation annotation.

**Comment by florina-muntenescu** [comment]
Feel free to ask this question on stackoverflow.
