### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Joslyn-Chen** [googlesamples/android-architecture-components#269]
Warning:警告: 来自注释处理程序 'android.arch.lifecycle.LifecycleProcessor' 的受支持 source 版本 'RELEASE_7' 低于 -source '1.8'
How to lift the warning

**Comment by iammert** [comment]
Duplicate https://github.com/googlesamples/android-architecture-components/issues/5

**Comment by 80998062** [comment]
...大哥你提issue能专业点吗

**Comment by Joslyn-Chen** [comment]
额，请问怎么专业提问？ @80998062
