### ISSUE TITLE
PagedList.BoundaryCallback-onItemAtEndLoaded() not be triggered

### ISSUE THREAD

**Issue by JiajunWong** [googlesamples/android-architecture-components#286]
I have a api which I can provide previous token ("token") and how many items ("limit").

At Api level I set limit = 20;
At LivePagedListBuilder level I also set it to 20;

First time I only used network layer which customized PageKeyedDataSource. Everything works perfectly.

Second time, I used database as DataSource and customized BoundaryCallback. Now the issue happens that whenever I got 60 item (onItemAtEndLoaded() called twice), the onItemAtEndLoaded() stops working. This issue never happened at First time.

Anyone also experienced this?

Thanks

**Comment by ChrisCraik** [comment]
Did you disable placeholders with setEnablePlaceholders(false)? That's currently broken for PositionalDataSources (which Room produces), but not other DataSources. Will be fixed in the next Paging Alpha release: https://issuetracker.google.com/issues/70573345

Workaround in the meantime is to enable placeholders.

**Comment by JiajunWong** [comment]
@ChrisCraik 
Thanks for sharing this. 
setEnablePlaceholders(true) works for me!

**Comment by jnahansen** [comment]
I'm using Paging Library 1.0.1 w/ Lifecycle:Extensions 1.1.1 but I'm not using ViewModel,Room,LiveData.
My PagedKeyedDataSource does the initial fetch (6 items) but never fetches more data on scroll to bottom. I added a BoundaryCallback but its never called. I've tried w/ Placeholders both on and off. My pagedList config is like:
 mPagingConfig = (new PagedList.Config.Builder())
                .setPageSize(6)
                .setPrefetchDistance(2)      
                .setInitialLoadSizeHint(6)      
                .setEnablePlaceholders(false)
                .build();
Any idea how to debug this or what I might be doing wrong?

**Comment by vikas0** [comment]
@jnahansen did you find a solution, it never gets called for me too,

**Comment by umairkhancis** [comment]
Any solution uptil now?

**Comment by victorferrucy** [comment]
@jnahansen Did you find the solution for your problem? Here, methods from the BoundaryCallback are not called too.

**Comment by charlieaboumoussa** [comment]
Same. I think it has to do with invalidating the DataSource to get a new one. So any updates on this? @ianhanniballake

**Comment by charlieaboumoussa** [comment]
> 
> 
> I'm using Paging Library 1.0.1 w/ Lifecycle:Extensions 1.1.1 but I'm not using ViewModel,Room,LiveData.
> My PagedKeyedDataSource does the initial fetch (6 items) but never fetches more data on scroll to bottom. I added a BoundaryCallback but its never called. I've tried w/ Placeholders both on and off. My pagedList config is like:
> mPagingConfig = (new PagedList.Config.Builder())
> .setPageSize(6)
> .setPrefetchDistance(2)
> .setInitialLoadSizeHint(6)
> .setEnablePlaceholders(false)
> .build();
> Any idea how to debug this or what I might be doing wrong?

Same. I think it has to do with invalidating the DataSource to get a new one. No placeholders are appearing so there are no nulls or LoadingObjects in the list of the adapter. So any updates on this? @billy-lau @keyboardsurfer @tnorbye @yaraki @DanAlbert @nickdesaulniers @jnahansen

**Comment by nickdesaulniers** [comment]
Please don't cc everyone like that.  I work on the kernel and C++ compiler, I have no idea what any of this is.

**Comment by charlieaboumoussa** [comment]
Sorry I thought this team works on the viewpager for android.
