### ISSUE TITLE
How to transform LiveData<ApiResponse<RequestTyp>> to LiveData<Resource<ResultType>>

### ISSUE THREAD

**Issue by khalid64927** [googlesamples/android-architecture-components#288]
My use case is only to get data from Network call, No database required and I'm struggling to understand how can i transform from network response type, which is `LiveData<ApiResponse<RequestType>>` to  `LiveData<Resource<ResultType>>` as required by 
success function of Resource class .

I've been tinkering upon the sample, below is the modified version of fetchFromNetwork function 
Note: I know i don't have to use MediatorLiveData since there is no more database.

```
private void fetchFromNetwork(final LiveData<ResultType> dbSource) {
        LiveData<ApiResponse<RequestType>> apiResponse = createCall();
        result.addSource(apiResponse, response -> {
            result.removeSource(apiResponse);
            if (response.isSuccessful()) {
                
                //  How to send back the received `response` back to caller with `setValue()`
                //      result.addSource(loadFromDb(),
                          // newData -> setValue(Resource.success(newData))) 
            } else {
                onFetchFailed();
                
            }
        });
    }
```

**Comment by khalid64927** [comment]
It was simpler than I thought it would be, but it took a while to understand why this ResultType and RequestType.

Below map operator did the the job were I pull all items off the response to make it ResultType here.

apiResponseLiveData = LiveData<ApiResponse<RequestType>> 

`LiveData<List<Repo>> repoList = Transformations.map(apiResponseLiveData, input -> input.body.getItems()`

**Comment by saurabhmdh** [comment]
Hi Khalid, 

I am also facing same issue where i don't want to use database.

    private void fetchFromNetwork() {
        LiveData<ApiResponse<RequestType>> apiResponse = createCall();
        result.addSource(apiResponse, response -> {
            result.removeSource(apiResponse);
            //noinspection ConstantConditions
            if (response.isSuccessful()) {
                appExecutors.diskIO().execute(() -> {
                    saveCallResult(processResponse(response));
                });
                **result.setValue(Resource.success(response.body));** // I am getting error here while setting the result. 
            } else {
                onFetchFailed();
            }
        });
    }

Can you post your solution

**Comment by shanuka** [comment]
Hi You can use following code for Network only 
~~~
abstract class NetworkOnlyBoundResource<ResultType, RequestType> @MainThread
internal constructor(private val appExecutors: AppExecutors) {

    private val result = MediatorLiveData<Resource<RequestType>>()

    init {
        result.value = Resource.loading(null)
        // LiveData<ResultType> dbSource = loadFromDb();

        val apiResponse = createCall()
        // result.addSource(apiResponse, newData -> result.setValue(Resource.loading(newData.body)));
        result.addSource(apiResponse) { response ->

            when (response) {
                is ApiSuccessResponse -> {
                    appExecutors.mainThread().execute {
                        // reload from disk whatever we had
                        result.value = Resource.success(response.body)
                        asLiveData()
                    }
                }

                is ApiEmptyResponse -> {
                    appExecutors.mainThread().execute {
                        // reload from disk whatever we had
                        result.value = Resource.success(null)
                        asLiveData()
                    }
                }

                is ApiErrorResponse -> {

                    result.value = Resource.error(response.errorMessage, null);
                    onFetchFailed()
                }

            }

        }

    }


    protected fun onFetchFailed() {}

    fun asLiveData(): LiveData<Resource<RequestType>> {
        return result
    }

    @MainThread
    protected abstract fun createCall(): LiveData<ApiResponse<RequestType>>
}
~~~

Example 
~~~

fun getDestination(): LiveData<Resource<List<Destination>>> {
        return object : NetworkOnlyBoundResource<List<Destination>, List<Destination>>(appExecutors) {
            override fun createCall(): LiveData<ApiResponse<List<Destination>>> {
                return githubService.getDestination();
            }
        }.asLiveData()
    }
~~~

if you need java source let me know

**Comment by Meirlen** [comment]
Can you give me java code ,please?

**Comment by PhalugunaRao** [comment]
> Hi You can use following code for Network only
> 
> ```
> abstract class NetworkOnlyBoundResource<ResultType, RequestType> @MainThread
> internal constructor(private val appExecutors: AppExecutors) {
> 
>     private val result = MediatorLiveData<Resource<RequestType>>()
> 
>     init {
>         result.value = Resource.loading(null)
>         // LiveData<ResultType> dbSource = loadFromDb();
> 
>         val apiResponse = createCall()
>         // result.addSource(apiResponse, newData -> result.setValue(Resource.loading(newData.body)));
>         result.addSource(apiResponse) { response ->
> 
>             when (response) {
>                 is ApiSuccessResponse -> {
>                     appExecutors.mainThread().execute {
>                         // reload from disk whatever we had
>                         result.value = Resource.success(response.body)
>                         asLiveData()
>                     }
>                 }
> 
>                 is ApiEmptyResponse -> {
>                     appExecutors.mainThread().execute {
>                         // reload from disk whatever we had
>                         result.value = Resource.success(null)
>                         asLiveData()
>                     }
>                 }
> 
>                 is ApiErrorResponse -> {
> 
>                     result.value = Resource.error(response.errorMessage, null);
>                     onFetchFailed()
>                 }
> 
>             }
> 
>         }
> 
>     }
> 
> 
>     protected fun onFetchFailed() {}
> 
>     fun asLiveData(): LiveData<Resource<RequestType>> {
>         return result
>     }
> 
>     @MainThread
>     protected abstract fun createCall(): LiveData<ApiResponse<RequestType>>
> }
> ```
> 
> Example
> 
> ```
> 
> fun getDestination(): LiveData<Resource<List<Destination>>> {
>         return object : NetworkOnlyBoundResource<List<Destination>, List<Destination>>(appExecutors) {
>             override fun createCall(): LiveData<ApiResponse<List<Destination>>> {
>                 return githubService.getDestination();
>             }
>         }.asLiveData()
>     }
> ```
> 
> if you need java source let me know

Hi can you tell NetworkOnlyBoundResource with flow not livedata
