### ISSUE TITLE
[all] Import from Android Studio failed

### ISSUE THREAD

**Issue by StephaneBausseron** [googlesamples/android-architecture-components#292]
Android Studio allows to import sample from this repository.

But the import cannot works as expected becauses all projects gradle includes "../version.gradle", but on import, android studio does not retrieves this file.

Step to reproduce:
1. Start Android Studio
2. From Splash Screen, click on "Import sample"
3. Choose a sample provided by this repository (in my example: "Architecture Components Paging")
4. Finish the wizard (set a location, etc.)
5. Wait a moment, then gradle script failed with error 
"Error:Could not read script '/home/steph/toto/versions.gradle' as it does not exist.".

Workaround: Clone the repository directly and do not use sample import feature.
for Architecture Components?

**Comment by florina-muntenescu** [comment]
Fixed meanwhile
