### ISSUE TITLE
No source code added for the "Guide to App Architecture"

### ISSUE THREAD

**Issue by SergeyVolynkin** [googlesamples/android-architecture-components#296]
about: https://developer.android.com/topic/libraries/architecture/guide.html
As a "Guide" Guide to App Architecture should provide source code of example project, but it don't. Because of that some points of the tutorial hard to understand as an example what is class "Status" of the field status in class Resource is. Is it our Class or imported one from Android.os package

Please add this example on googlesamples github

**Comment by AkshayChordiya** [comment]
The GitHubBrowserSample app of this repository is an example project for "Guide to App Architecture" mentioned at [Guide to App Architecture](https://developer.android.com/topic/libraries/architecture/guide.html)

**Comment by EmileKroeger** [comment]
I agree with Sergey that a sample would be very helpful to go along with that guide to app architecture. The github example you give is considerably more complicated, and I can't find an example of the simpler project described in that article.
