### ISSUE TITLE
[QUESTION] Can we intregrade android-priority-jobqueue with LiveData and ViewModel ?

### ISSUE THREAD

**Issue by nicolasjafelle** [googlesamples/android-architecture-components#30]
@yigit is it relatively simple to integrate your's android-priority-jobqueue with this new Arch Components? I am wondering where will be the ideal place to do the "async task" operation. Thanks in advance!

**Comment by yigit** [comment]
JobManager excels in things like persisting jobs, priority or handling network conditions; none of which were necessary for this demo so we've not used it (or any other job manager library).
If we were to integrate it with this app, it would replace part of `AppExecutors` and the tasks in repository would probably be jobs that execute network requests in sync mode.
So to answer your question, repository would be the one using the job manager to handle background operations.

**Comment by nicolasjafelle** [comment]
Thanks! @yigit Really helpfull all your explanation! Lesson learned =D.

**Comment by gaurav414u** [comment]
Thanks @yigit . Repository + JobManager seems to be a kick-ass combination.
