### ISSUE TITLE
i resolve a bug

### ISSUE THREAD

**Issue by IlikeJay** [googlesamples/android-architecture-components#300]
in the TO-DO-MVP Demo com.example.android.architecture.blueprints.todoapp.tasks.view.TasksFragment#showNoTasks，the third paramter is always false,so the textview（R.id.noTasksAdd） defined int the xml but it  is never visiable ,lol.

**Comment by florina-muntenescu** [comment]
Looks like this is not related to this set of samples, but to the [Architecture Blueprints](github.com/googlesamples/android-architecture). Create it in the right project.
