### ISSUE TITLE
The ../versions.gradle is not included when importing from Android Studio

### ISSUE THREAD

**Issue by LouisCAD** [googlesamples/android-architecture-components#303]
I mean... I have even tried the project? I wanted to import it from Android Studio, but it doesn't build because of this mysteriously missing file.

**Comment by JoseAlcerreca** [comment]
Dup of #259 

That AS integration doesn't seem to be compatible with the way the versions are configured.

Just git clone the whole repo for now, and we'll work on a fix.

Thanks!

**Comment by LouisCAD** [comment]
Alright, thanks for your reactivity!
