### ISSUE TITLE
AndroidViewModel doesnot update the resources with locale changes

### ISSUE THREAD

**Issue by prabinshrestha** [googlesamples/android-architecture-components#308]
I have an application that supports locale changes but when i try to change, the local resources with context changes but when i do the same in AndriodViewModel it doesnot work with application

*context.getResources().getString(R.string.sample) , this work if it is activity context *application.getResources().getString(R.string.sample), this fails to support locale support

Here is my viewmodel sample where i try to application.getResources().getString(R.string.sample) but fails to get locale change text

public class SampleViewModel extends AndroidViewModel {

    private Application application;
    public SampleViewModel(Application application) {
        super(application);
        this.application =  application;
    }

    public List<Species> getSampleList() {
       List<Sample> sampleList = new ArrayList<>();
      sampleList.add(new Sample(application.getResources().getString(R.string.sample));
       sampleList.add(new Sample(application.getResources().getString(R.string.sample));
       return sampleList;
   }

and i updated in activity as well as application
 (in activity i override this)
 @Override
    protected void attachBaseContext(Context base) {
      super.attachBaseContext(LocaleManager.setLocale(base));
    }

 (in application i override this)
    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(LocaleManager.setLocale(base));
}

public class LocaleManager {

    public static Context setLocale(Context c) {
        return updateResources(c, getLanguage(c));
    }

    private static Context updateResources(Context context, String language) {
        Locale locale = new Locale(language);
        Locale.setDefault(locale);

        Resources res = context.getResources();
        Configuration config = new Configuration(res.getConfiguration());
        if (Build.VERSION.SDK_INT >= 17) {
            config.setLocale(locale);
            context = context.createConfigurationContext(config);
        } else {
            config.locale = locale;
            res.updateConfiguration(config, res.getDisplayMetrics());
        }

        return context;
    }

}

**Comment by florina-muntenescu** [comment]
This is not an issue with the samples. 
if this is an issue with the components, please use the [official issue tracker]( https://issuetracker.google.com/issues?q=componentid=197448%20status:open&s=modified_time:desc) to report it.

**Comment by palvijay** [comment]
I believe you may need to reload your activity/fragment after changing locale.

**Comment by LoAlex** [comment]
try to update your config of application context, instead of activity/fragment context, 
it works for me.

val config = context.applicationContext.resources.configuration
        Locale.setDefault(locale)
        config.locale = locale
        context.applicationContext.getResources().updateConfiguration(config, context.applicationContext.getResources().getDisplayMetrics());

**Comment by ronem123** [comment]
Affected by same problem. I wished to create method in viewmodel with the args of string(localized) which will be passed from fragment or activity.
