### ISSUE TITLE
[GitHubBrowserSample] RepoFragmentTest broken

### ISSUE THREAD

**Issue by ChrisCraik** [googlesamples/android-architecture-components#312]
Broken by this patch:

https://github.com/googlesamples/android-architecture-components/commit/330481ac0ab6bd7b28230fe7abdac857b155dad1

Locally reverting that change makes the test pass again. @JoseAlcerreca Patch looks benign, any idea why?

**Comment by florina-muntenescu** [comment]
Fixed.
