### ISSUE TITLE
Why Completable/Single is not supported as direct return type for @Insert or @Delete methods in @Dao?

### ISSUE THREAD

**Issue by PPetka** [googlesamples/android-architecture-components#316]
I am wondering if there is a contradiction for a RxJava/Room to be able to return **Completable/Single** types directly from methods annotated with @Insert or @Delete annotations in class annotated with **@Dao**

For example
In my **@Dao**, I have function like

```
@Insert(onConflict = OnConflictStrategy.REPLACE)
fun insert(model: SomeObject)
```

when switching to RxJava2 I wrote
```
@Insert(onConflict = OnConflictStrategy.REPLACE)
fun insert(model: SomeObject) : Completable
```
and later

```
@Insert(onConflict = OnConflictStrategy.REPLACE)
fun insert(model: SomeObject) : Single<Long>
```
but compiler yells at me that **@Insert** can return either void or Long type.

I thought I have made mistake somewhere and writing this way is acceptable, but after investigating an official RxJava + Room sample.

 [I can see code (line 59) ](https://github.com/googlesamples/android-architecture-components/blob/master/BasicRxJavaSample/app/src/main/java/com/example/android/observability/ui/UserViewModel.java)similar to:

```
return Completable.fromAction(() -> {
      dao.insert(.....)
}
```

Pojo is wrapped into completable so it can be thrown into RxChain

If Room is able to return RxObjects From @Query annotation, why can't it return them from **@Insert, @Delete** aswell, and we are forced to wrap them ourselves if we want to keep DB api consistent.

Thanks

**Comment by florina-muntenescu** [comment]
This issue has already been reported on the official issue tracker [here](https://issuetracker.google.com/63613835).
Please only create issues related to the samples here. More info on this can be found in the issue template.

**Comment by PPetka** [comment]
@florina-muntenescu 
Thanks for reply. Good to know this issue is already reported.
Gotta keep in mind, to post architecture components bugs/feature proposal in google bug tracker in future
