### ISSUE TITLE
Handling onActivityResult with LifecycleObserver

### ISSUE THREAD

**Issue by savjolovs** [googlesamples/android-architecture-components#317]
Hello. I'm wondering is there any way of handling onActivityResult() with LifecycleObserver? I have checked Lifecycle.Event class that contains all the available lifecycle events and looks like there is no event for hading onActivityResult().
Why there is no corresponding event for onActivityResult? Is it something that will be added later or it's not there on purpose?

Use case for this: Moving "sign in with Facebook" functionality in separate class. Facebook SDK requires to call 
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    callbackManager.onActivityResult(requestCode, resultCode, data)
    super.onActivityResult(requestCode, resultCode, data)
}
```

Thank you!

**Comment by hshahdoost** [comment]
I also see it is cool to have callbacks such as `onActivityResult` and `onRequestPermissionsResult` as the lifecycle events.

**Comment by florina-muntenescu** [comment]
This is not an issue with the samples. Please use the [official issue tracker](https://issuetracker.google.com/issues?q=componentid=197448%20status:open&s=modified_time:desc) for issues or feature requests.
