### ISSUE TITLE
PaginSample Gradle build fails 'cuz of Diffutil.ItemCallback

### ISSUE THREAD

**Issue by kendhia** [googlesamples/android-architecture-components#319]
## PaginSample buliding fails
I cloned the PagingSample and try to build it without making any change, but it keeps failing cuz of an error in the following code: 
```private val diffCallback = object : DiffUtil.ItemCallback<Cheese>() {
            override fun areItemsTheSame(oldItem: Cheese, newItem: Cheese): Boolean =
                    oldItem.id == newItem.id

            /**
             * Note that in kotlin, == checking on data classes compares all contents, but in Java,
             * typically you'll implement Object#equals, and use it to compare object contents.
             */
            override fun areContentsTheSame(oldItem: Cheese, newItem: Cheese): Boolean =
                    oldItem == newItem
        }
```
with an error `Uresolved reference : ItemCallback` 

Does any one have an idea why this is happening ?

**Comment by pedroimai** [comment]
Same problem here. Fixed it updating Support lib. to version 27.1.0 and Paging to 1.0.0-alpha6

**Comment by abhi9044** [comment]
The above solution didn't worked for me, I went 1 commit back and things were fine then, I was able to build and run the project.

**Comment by fatjoem** [comment]
I created a pull request with @pedroimai 's fix at https://github.com/googlesamples/android-architecture-components/pull/323
