### ISSUE TITLE
ViewModel's onCleared is not be call after fragment is destroyed.

### ISSUE THREAD

**Issue by Guaidaodl** [googlesamples/android-architecture-components#337]
I have a very simple ViewModel.
``` Kotlin
class TestViewModel: ViewModel() {
    override fun onCleared() {
        super.onCleared()
        Log.d("TEST", "clear")
    }
}
```
and I use it in a fragment
``` Kotlin
class TestFragment() {
    //....
    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        vm = ViewModelProviders.of(this).get(TestViewModel::class.java)
    }
}
```
and the onCleared method is not be called after activity finished.  

If I want the method to be called, I have to remove fragment manually before finish activity.

I am not sure it is feature or bug.

**Comment by JoseAlcerreca** [comment]
This is a known bug, already fixed in 27.1.1.
https://developer.android.com/topic/libraries/support-library/revisions.html

Please report bugs in the library in the correct tracker. This is just for samples.

**Comment by Guaidaodl** [comment]
@JoseAlcerreca Thank you

**Comment by AndroidDeveloperLB** [comment]
@JoseAlcerreca  Was it fixed on 27.1.1 ? Or found? Is there a workaround?
Someone claimed it was fixed only on 28.0.0 : https://stackoverflow.com/a/49411448/878126

**Comment by CeH9** [comment]
What's about same bug in androidX?
**androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0-alpha05**

**Comment by zakrodionov** [comment]
Same bug in androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0-alpha05

**Comment by jemshit** [comment]
Exists in v2.1.0 (stable) too

**Comment by tudorgk** [comment]
I found that it's still an issue on 2.2.0 when having fragments as pages in ViewPager2.

**Comment by Vlad-Shesternin** [comment]
For a stable onCleared call, the following version works well: 
def view_model = "2.3.0-alpha03"
implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$view_model"

**Comment by AndroidDeveloperLB** [comment]
@Vlad-Shesternin There is already a newer version:

androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0-beta01

**Comment by aliguvenc** [comment]
viewmodel is not being cleared still for version 2.3.1

**Comment by kartik0198** [comment]
Any update on this? Such a major bug which is still not fixed. Please google, fix this asap.

**Comment by HassanAlizadehDevlab** [comment]
This issue is still available in newer versions. Is there any open issue for this problem?

**Comment by rmirabelle** [comment]
I'm completely unable to use ViewModel with DialogFragment, if the dialog will be created more than once.  Once the dialog subscribes to the ViewModel, then is destroyed, the ViewModel is not cleared.  No other components use the VM. This occurs whether I subscribe via `observe(this, {})` or `observe(viewLifecycleOwner, {})`.

**Comment by Robotecom** [comment]
@JoseAlcerreca @yigit
I also face the same problem. Now, I can not use hilt to inject viewmodels into activities cause creating viewmodels this way won't trigger onCleared function causing memory leaks

**Comment by tr15tan** [comment]
> After wasting ANOTHER day troubleshooting why my `ViewModel` wasn't being cleared when my `DialogFragment`'s `onDestroy` method was called, I think I've isolated the culprit. In my `DialogFragment`, I was instantiating the VM this (wrong) way;
> 
> `private val vm: MyViewModel by activityViewModels()`
> 
> Changing it to this (right) way solved it:
> 
> `private val vm: MyViewModel by viewModels()`
> 
> Apparently, the `by activityViewModels` delegate automatically scopes the VM lifetime to the lifetime of `DialogFragment`'s host `Activity` instead of the `DialogFragment` itself. I think this explains why the VM wasn't clearing. I'll save ranting about the absurd complexity of Android for another post.

In my case, using `by activityViewModels()` lead to onCleared() never be called, and using `by viewModels()` make onCleared() is only called once, which is worse...

**Comment by balwinderSingh1989** [comment]
Issue still exists in 2.4.1

**Comment by pablobaldez** [comment]
Do you have some updates related to this issue?

**Comment by devanshukaushik** [comment]
For users who have this issue with `fragments` linked to `BottomNavigationView`, the `viewModel` might not be getting cleared due to the support added for multiple back stacks. You can refer to [this article by Ian Lake](https://medium.com/androiddevelopers/multiple-back-stacks-b714d974f134) where he talks about when exactly a `fragment` is removed from such back stacks and consequently the view model scoped to them is cleared.

Credits to [this reddit thread by u/psteiger](https://www.reddit.com/r/androiddev/comments/u555bl/why_is_a_viewmodel_scoped_to_the_fragment_of_a/).
