### ISSUE TITLE
Data-Binding using LiveData

### ISSUE THREAD

**Issue by gaurav414u** [googlesamples/android-architecture-components#34]
in Basic Sample, ProductFragment.java
```
// Observe product data
model.getObservableProduct().observe(this, new Observer<ProductEntity>() {
    @Override
    public void onChanged(@Nullable ProductEntity productEntity) {
        model.setProduct(productEntity);
   }
});
```
We observe for a change in ```LiveData<ProductEntity> mObservableProduct```. When a change is there we set ```ObservableField<ProductEntity> product``` so that the data-binding library updates the UI. It seems like too much work perhaps.

My understanding would be that since LiveData cares about the lifecycle owner and not the view, hence databinding doesn't support LiveData. Is that so? @yigit 
If this is the right way of doing it, is there any better way of using Data-Binding with LiveData?

**Comment by iammert** [comment]
@BindingAdapter will solve your problem. In my case I need to update list on LiveData has changed. Here is how I achieve this by using databinding.

I created a BindingAdapter to update list.
```java
public final class ListBindingAdapter{
    @BindingAdapter(value = "resource")
    public static void setResource(RecyclerView recyclerView, Resource resource){
        RecyclerView.Adapter adapter = recyclerView.getAdapter();
        if(adapter == null)
            return;

        if(resource == null || resource.data == null)
            return;

        if(adapter instanceof BaseAdapter){
            ((BaseAdapter)adapter).setData((List) resource.data);
        }
    }
}
```
Then I need to add list as variable to my xml.
```xml
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>
        <variable
            name="resource"
            type="iammert.com.androidarchitecture.data.Resource"/>
    </data>

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:resource="@{resource}"/>

</layout>
```
Then, all I need to do is setResource on live data change.
```java
movieListViewModel
                .getPopularMovies()
                .observe(this, listResource -> binding.setResource(listResource));
```

**Comment by yigit** [comment]
We are going to make data binding lifecycle aware but for that to happens, lifecycle needs to hit 1.0 stable api.

**Comment by theanh0512** [comment]
@iammert  ((BaseAdapter)adapter) how you cast RecyclerView adapter to BaseAdapter?

**Comment by rachitmishra** [comment]
@iammert how do we test that part :)

**Comment by addmoremobile** [comment]
@yigit as of 1.0.0 is out now, is it now possible to bind livedata?

**Comment by iammert** [comment]
@theanh0512 I created BaseAdapter abstract class which has setData(List<T> data).

**Comment by iammert** [comment]
@yigit @JoseAlcerreca Hey! Thanks for stable version! It is already hit to the stable version. Do you have any update about making databinding lifecycle aware?

**Comment by gaurav414u** [comment]
@yigit @JoseAlcerreca Hi! I think, its time to reopen this bug as the lifecycle has already hit 1.0 stable api.
Thoughts?

**Comment by wsura** [comment]
LiveData without data binding kinda makes little sense, because you have to set/listen your way through again or manually throw data between observables and LiveData and that increases amount of vode required to present data, not decreases. @yigit, it definitely needs revising - especially, that you already hit 1.0 stable. Please reopen.

**Comment by a141199** [comment]
Keen to see this happen also.

**Comment by rhexgomez** [comment]
The above proposal is interesting and make sense  so I really want this thread to re-open.

**Comment by jereksel** [comment]
It seems like it's possible now with new Canary build: https://androidstudio.googleblog.com/2017/12/android-studio-31-canary-6-is-now.html

"You can now use a LiveData object as an observable field in data binding expressions. The ViewDataBinding class now includes a new setLifecycle method that you need to use to use to observe LiveData objects."

**Comment by erikcaffrey** [comment]
I created a project sample to show how works Live Data + Data Binding maybe can be useful for someone.  https://github.com/erikcaffrey/LiveData-DataBinding-Kotlin

**Comment by stabib** [comment]
Here's another implementation by @pszklarska: 
https://github.com/pszklarska/LiveDataBinding

**Comment by filipkowicz** [comment]
note that it's working for two-way data binding also!
