### ISSUE TITLE
Room (possibly others) dont seem to compile with Java 8

### ISSUE THREAD

**Issue by RichyHBM** [googlesamples/android-architecture-components#35]
I am getting this error specifically by trying to use kotlin with Room, but I assume this would also occur if you are using Java 8 in your source code.

The error is: `Warning:warning: Supported source version 'RELEASE_7' from annotation processor 'android.arch.persistence.room.RoomProcessor' less than -source '1.8'` and seems to be from a use of `@SupportedSourceVersion` which specifies "the latest source version an annotation processor supports"? Is this expected? Do we need to wait for the full 1.0 release for it to be fully supported?

**Comment by mynote** [comment]
Its a warning, not an error. If you use Java 8 features like Lambdas, its just a warning that rooms annotation processor uses java 7 for generating their code. Ignore it since it doesnt hurt.  I guess its used in room to let developers decide if they want to use java 8 (annotations) or 7.

**Comment by yigit** [comment]
Yes, it is just a warning. Should not be a problem.

**Comment by kenyee** [comment]
Would be nice if there were a Gradle flag we could use to turn this warning off...it's the only warning in our project build :-(

**Comment by mttmllns** [comment]
Another vote for patching this up somehow.  It's the only thing keeping us from treating warnings as errors.

**Comment by ezamelczyk** [comment]
Just pass `-Xlint:unchecked` to your Gradle flags until Google decides to support Java 8 like in lifecycle library.

**Comment by aldoKelvianto** [comment]
If somebody still encounter this warning, I suggest changing `compiler` in `annotationProcessor`

```git
-    annotationProcessor "android.arch.lifecycle:compiler:1.0.0"
+    annotationProcessor "android.arch.lifecycle:common-java8:1.0.0"
```

In my project the warning disappear. I hope this helps.

**Comment by miketrewartha** [comment]
That gets rid of the warning for the `lifecycle` stuff, but not for the Room stuff.

**Comment by MohamedISoliman** [comment]
I have the same problem but I don't know how to solve I'm using Android studio 3.10

**Comment by SerggioC** [comment]
So many bugs...

**Comment by successanil** [comment]
upgrade to room 1.1.1, java 8 and warning will disappear.

**Comment by shekharartemedia** [comment]
i have update the room version but still i getting the same issue. Please help.

**Comment by vinisantos630** [comment]
Boa noite pessoal, estou com o mesmo problema só que em Java, para gerar relatórios no JasperReport Studio, segue abaixo a mensagem:

net.sf.jasperreports.engine.design.JRJdk13Compiler compileClasses
INFORMAÇÕES: warning: Supported source version 'RELEASE_8' from annotation processor 'net.sf.jasperreports.annotations.processors.properties.PropertyProcessor' less than -source '17'
1 warning

Entendi que é um aviso, mas o executável não deixa gerar o relatório por conta desse "erro", alguém conseguiu uma solução?

**Comment by sebm123** [comment]
> I am getting this error specifically by trying to use kotlin with Room, but I assume this would also occur if you are using Java 8 in your source code.
> 
> The error is: `Warning:warning: Supported source version 'RELEASE_7' from annotation processor 'android.arch.persistence.room.RoomProcessor' less than -source '1.8'` and seems to be from a use of `@SupportedSourceVersion` which specifies "the latest source version an annotation processor supports"? Is this expected? Do we need to wait for the full 1.0 release for it to be fully supported?

**Comment by sebm123** [comment]
[Uploading OpenMQTTGateway-development.zip…]()

**Comment by thewyp** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
