### ISSUE TITLE
DaggerAppComponent not part of 2.15

### ISSUE THREAD

**Issue by joshuaherman** [googlesamples/android-architecture-components#350]
https://github.com/googlesamples/android-architecture-components/blob/d7cd7a9414ef1eeba52a79ec76f6d9827cd50a36/GithubBrowserSample/app/src/main/java/com/android/example/github/di/AppInjector.kt#L35

**Comment by Zhuinden** [comment]
It's generated code. You need to rebuild the project to use it.

**Comment by joshuaherman** [comment]
Yeah I figured this out 30 minutes after making this issue. Leaving this here for for fellow devs. 

Make a component and a module supplying all provides out requirements.
