### ISSUE TITLE
TableInfo.Column notNull Not expected

### ISSUE THREAD

**Issue by YougaKing** [googlesamples/android-architecture-components#351]
![image](https://user-images.githubusercontent.com/16010591/39657687-f6005c54-503c-11e8-8ef8-c771b245f5b6.png)
![image](https://user-images.githubusercontent.com/16010591/39657694-01d299a2-503d-11e8-9455-2e62345daa76.png)
I want
![image](https://user-images.githubusercontent.com/16010591/39657715-336e4f60-503d-11e8-8ff8-053433f529b2.png)
how to do

**Comment by yigit** [comment]
integers are primitives so they cannot be null.

**Comment by yigit** [comment]
you can change it to be an Integer if you want it to be nullable.
