### ISSUE TITLE
Please provide all samples in Java

### ISSUE THREAD

**Issue by kagile** [googlesamples/android-architecture-components#370]
Kotlin code is not readable. Why are samples not written in Java?

Btw, Kotlin is the worst thing introduced for Android.

**Comment by JoseAlcerreca** [comment]
I suggest you give it a go. You will immediately see benefits and it's not that different once you get the basic concepts.

We'll take into account your feedback though. Thanks.

**Comment by kagile** [comment]
I have been using it for a year

**Comment by kagile** [comment]
It may be easy to write but not read.

**Comment by kagile** [comment]
I'm fine with the simplicity of Java. You should provide all the samples in Java.

**Comment by kagile** [comment]
Btw, You can easily create a mess in Kotlin.
