### ISSUE TITLE
Faild to resovled

### ISSUE THREAD

**Issue by jinyb09017** [googlesamples/android-architecture-components#38]
when I gradlew build the BasicSample, i got error
logs:

A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve android.arch.persistence.room:support-db:1.0.0-alpha1.
     Required by:
         project :app > android.arch.persistence.room:runtime:1.0.0-alpha1
         project :app > android.arch.persistence.room:runtime:1.0.0-alpha1 > android.arch.persistence.room:support-db-impl:1.0.0-alpha1
      > Could not resolve android.arch.persistence.room:support-db:1.0.0-alpha1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/android/arch/persistence/room/support-db/1.0.0-alpha1/support-db-1.0.0-alpha1.pom'.
            > Could not HEAD 'https://dl.google.com/dl/android/maven2/android/arch/persistence/room/support-db/1.0.0-alpha1/support-db-1.0.0-alpha1.pom'.
               > dl.google.com`

i don't think this is network error. because i has set proxy. who knows why

**Comment by JoseAlcerreca** [comment]
Dup of #25 ?

**Comment by jinyb09017** [comment]
perhaps not same @JoseAlcerreca .
that error occur when i follow the solution that they said.

**Comment by jinyb09017** [comment]
经发现https://dl.google.com/dl/android/maven2/android/arch/persistence/room/support-db/1.0.0-alpha1/support-db-1.0.0-alpha1.pom下载后的目录\.gradle\caches\modules-2\files-2.1\android.arch.persistence.room\support-db\1.0.0-alpha1\1db084aa6b150b4b7059ec92cba2f9ca7011bfa6的support-db-1.0.0-alpha1.pom文件竟然是乱码，导致无法解析，以及无法下载对应的jar和aar.所以直接通过浏览器下载后，覆盖这个文件即解决问题了。

另外工程需要android studio 3.0才能运行
