### ISSUE TITLE
PagingRequestHelper does not exists in documentation yet it's in samples

### ISSUE THREAD

**Issue by GregSaintJean** [googlesamples/android-architecture-components#397]
[PagingRequestHelper](https://github.com/googlesamples/android-architecture-components/blob/master/PagingWithNetworkSample/app/src/main/java/com/android/example/paging/pagingwithnetwork/reddit/util/PagingRequestHelperExt.kt) contains the import android.arch.paging.PagingRequestHelper. But when you [look it up in the developer docs](https://developer.android.com/s/results/?q=PagingRequestHelper&p=%2F), the class does not exists. I'm trying to find how the code works and recreate it.

**Comment by Zhuinden** [comment]
It's [here](https://github.com/googlesamples/android-architecture-components/blob/a4c17b2a1ea86b113edd5c82cc3abc4205a02c91/PagingWithNetworkSample/app/src/main/java/android/arch/paging/PagingRequestHelper.java)

**Comment by GregSaintJean** [comment]
Ah. Wonderful. I remembered that path but it didn't come to mind to go back up the file hierarchy. Okay. Thank you @Zhuinden

**Comment by TonyTangAndroid** [comment]
Might I ask why it is named under package `android.arch.paging`, but it is not listed in the code of Paging library? It would be not convenient for any one who uses such class to copy it in their own project, which also adds maintainability responsibility that is error-prone.

**Comment by antarikshc** [comment]
Is this going to be part of Jetpack Paging library?

Updated [Link](https://github.com/android/architecture-components-samples/blob/master/PagingWithNetworkSample/app/src/main/java/androidx/paging/PagingRequestHelper.java)

**Comment by Zhuinden** [comment]
It was not added into Paging 1.x and 2.x, and 3.x is going to be rewritten entirely. Probably not.

**Comment by jQrgen** [comment]
Does this exist in any library now?

**Comment by Zhuinden** [comment]
They said *likely* to be moved into the lib, now it's unlikely :wink:

**Comment by dlam** [comment]
APIs for refresh, retry and load state (including errors) are now built into Paging3, so I can confirm there are no longer any plans to release `PagingRequestHelper` as part of Paging.
