### ISSUE TITLE
Support transform items in a PagedList?

### ISSUE THREAD

**Issue by LanderlYoung** [googlesamples/android-architecture-components#412]
this is a repost of google issue tracker https://issuetracker.google.com/issues/111130543

Component used: PagingLibrary
Version used: 1.0.1
Devices/Android versions reproduced on: N/A

Android Architecture Component now introduced Paging Library, which is great.

According to the official demo The DataSource.Factory now supports map and mapByPage methods, which means we may transform items in one DataSource.

But DataSource and DataSource.Factory should be in the model/domain/data layer, not the Presenter/View layer. However, there are plenty of times when we want to transform data in our Adapter(for RecyclerView or ListView), and obviously, this is the Presenter/View layer logic. By now, an Adapter holds an instance of PagedList, but PageList can't support these operations, which is kinda awkward. Besides, there are still times when we want to add items or remove items to/from a PagedList.

So this is a feature request:

Support item transformations on a PagedList

Support item adding/removing to/from a PagedList

Thanks for consideration.

**Comment by ChrisCraik** [comment]
Chimed in on issue tracker. Since this is already captured in the google issue tracker and not related to samples, closing.
