### ISSUE TITLE
Hide fragments with Navigation

### ISSUE THREAD

**Issue by WebTiger89** [googlesamples/android-architecture-components#414]
Hi,
I took some time to check out the new Navigation lib. I like the clean implementation of app-in navigating. Unfortunately there is no option to hide/show fragments instead of replacing them. Is there a deeper reason behind this decision?

I think hiding fragments is useful especially for top-level (i.e. drawer) navigation because these are fragments that will be opened often. 

Some fragments are expensive to instatiate again and again and what about if I have a "ScannerFragment" showing a list with ble devices or state in general. I would lose the content every time I switch the fragment. Or is there a solution for this problem?

Thanks in advance

**Comment by sunlimiter** [comment]
The same question

**Comment by gavinzhangautogravity** [comment]
This question has been in my mind since I first started using this library.

**Comment by CajetanP** [comment]
Has anyone found a solution to this yet? Do I have to give up on the Navigation Component if I just want to show and hide a particular fragment?

**Comment by dishantkawatra** [comment]
Hello Guys Any one find the solution please let me know

**Comment by ianhanniballake** [comment]
Please file feature requests for Navigation on the [issue tracker](https://issuetracker.google.com/issues/new?component=409828) explaining your use case.

**Comment by HoomanAbedi** [comment]
Hi guys please let me know if you find a solution for this, i would really appreciate it.

**Comment by mochadwi** [comment]
@ianhanniballake is there any update about hide fragment for navigation components?

**Comment by chensixian** [comment]
@HoomanAbedi 
Just to remove `app:destination` attribute from `navigation action` .
[https://medium.com/@programmerr47/navigate-back-with-navigation-component-6cec37ba6964](https://medium.com/@programmerr47/navigate-back-with-navigation-component-6cec37ba6964)

**Comment by TsaiYongChuan** [comment]
Hi guys please let me know if you find a solution for this, i would really appreciate it.
