### ISSUE TITLE
Nav-Framework is nice, however, it create fragment's view every time when people click menu-item on drawer-layout

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/android-architecture-components#419]
I use NavController + DrawerLayout, set some menu-items on the drawer, it seems automatically setup the drawer, it's cool. But, each time I click one item on the drawer and click the same item several times, the Nav will navigate to the same fragment and onCreateView will be called each time, it's so SAD! It's definitive a bug because the initializing of a view is not cheap.

Any idea?

[issues](https://issuetracker.google.com/issues/111631295)

Same problem: https://github.com/googlesamples/android-sunflower/issues/117

**Comment by Mobator** [comment]
Hey guys! Have you tried to run the sunflower app? I've tried and noticed the following behavior: when the user navigates from PlantListFragment to PlantDetailFragment and go back, the PlantListFragment is unchanged (holds the same state after the navigation).

The bad thing is: when i try to create my own project with navigation, this behavior doesn't work. When the user goes back all the previous state is lost. Any of you had experienced something like that?

Thanks!

**Comment by aromano272** [comment]
> Hey guys! Have you tried to run the sunflower app? I've tried and noticed the following behavior: when the user navigates from PlantListFragment to PlantDetailFragment and go back, the PlantListFragment is unchanged (holds the same state after the navigation).
> 
> The bad thing is: when i try to create my own project with navigation, this behavior doesn't work. When the user goes back all the previous state is lost. Any of you had experienced something like that?
> 
> Thanks!


> Hey guys! Have you tried to run the sunflower app? I've tried and noticed the following behavior: when the user navigates from PlantListFragment to PlantDetailFragment and go back, the PlantListFragment is unchanged (holds the same state after the navigation).
> 
> The bad thing is: when i try to create my own project with navigation, this behavior doesn't work. When the user goes back all the previous state is lost. Any of you had experienced something like that?
> 
> Thanks!

That PlantListFragment keeps it's state because it doesn't get destroyed, when you click on an item and navigate to PlantDetailFragment it creates a new instance of DetailFragment and places it on top of the backstack, leaving the ListFragment alive.

When later on you press back, it navigates up, popping the DetailsFragment and leaving the ListFragment visible, meaning ListFragment was never recreated.

**Comment by lookashc** [comment]
Agreed with @aromano272 and @sociaxie. Inability of having proper backstack in nav controller is a huge productivity issue. Hope it's a missing feature or a work-around made on purpose... IMO this is a must-have and has to be introduced sooner rather than later.

**Comment by doomtrooper** [comment]
@ianhanniballake Can you please share your views on how to achieve the same, possibly with some example?

**Comment by kazaky** [comment]
@ianhanniballake

**Comment by shenguojun** [comment]
Temporary solution I think, for BottomNavigationView, you should try  [NavigationAdvancedSample](https://github.com/googlesamples/android-architecture-components/tree/master/NavigationAdvancedSample) this example which mentioned in [issue tracker](https://issuetracker.google.com/issues/80029773) for support multiple back stacks. And you should try to keep data in ViewModel and inflate layout with that data when fragment recreate. Most system provided view have already save its state in onSaveInstanceState, and you just need to make sure you keep the right data to restore the view state. For custom view, I think it's you responsibility to make your own SaveInstanceState logic.

**Comment by shenguojun** [comment]
@ianhanniballake maybe you can share you views on this issue before you close it

**Comment by Robotecom** [comment]
I for once thought that fragment is being recreated but after checking logs if found that it was not recreated. The thing that made me thought that way is because i was using extending LiveData and implementing onActive method which of course would be triggered whenever fragment stops and start again i.e. "When navigating forward and back again" .
In that overridden onActive method i was attaching the listener to query which result in making that query over and over whenever that onActive is triggered so i was getting more and more result which made me think that the fragment was being recreated when i navigate back.I hope this could help you.

**Comment by nvanh** [comment]
I've just faced the same issue and finally come up with the old way as follow:

1.
`currentDestinationId = navController.getGraph().getStartDestination();`

2.
`navigationView.setNavigationItemSelectedListener(this);`

3.
```
@Override
public boolean onNavigationItemSelected(@NonNull MenuItem item) {
	final boolean sameDestination = item.getItemId() == currentDestinationId;

	if (!sameDestination) {
		navController.navigate(item.getItemId());
		currentDestinationId = item.getItemId();
	}

	drawer.closeDrawer(GravityCompat.START);
	return true;
}
```

**Comment by Superblazer** [comment]
I do not know if this is the right way, but I did this for a Bottom Navigation Drawer

`        binding.navigation.setNavigationItemSelectedListener {

            when (it.itemId) {
                R.id.indiaFragment -> {
                    if (!it.isChecked) {
                        navController.navigate(R.id.indiaFragment)
                    } else {
                        it.isChecked = true
                    }
                }
                R.id.worldFragment -> if (!it.isChecked) {
                    navController.navigate(R.id.worldFragment)
                } else {
                    it.isChecked = true
                }
            }
            dismiss()
            true
        }
`

**Comment by Superblazer** [comment]
I did this for a Bottom Navigation Drawer
``
        binding.navigation.setNavigationItemSelectedListener {

            if (it.itemId != navController.currentDestination!!.id) {
                it.onNavDestinationSelected(findNavController())
            }

            this.dismiss()
            true
        }
``

**Comment by ashanajackol** [comment]
Android navigation component is suck, Better switch to old school method...

**Comment by zainkhalid91** [comment]
has anyone found the solution to it?

**Comment by shubhamp98** [comment]
Stiill on 2021, the same issue exist. Wow!

**Comment by ankitbatra11** [comment]
> has anyone found the solution to it?

I will share my solution to this. It is minimalistic as it re-uses the code from `NavigationUI`.

Register a destination change listener to keep your menu item checked status in sync with the current destination.

```
navController.addOnDestinationChangedListener((controller, destination, arguments) -> {
            for (int i = 0; i < navigationView.getMenu().size(); i++) {
                MenuItem menuItem = navigationView.getMenu().getItem(i);
                menuItem.setChecked(menuItem.getItemId() == destination.getId());
            }
        });
```

And register the below item selected listener to change the destination when a navigation menu item is clicked:
```
navigationView.setNavigationItemSelectedListener(item -> {
    if (item.getItemId() != navController.getCurrentDestination().getId()) {
        return NavigationUI.onNavDestinationSelected(item, navController));
    }
    return false;
}
```

That's it!

**Comment by Aravindh1505** [comment]
Still, the issue exists!. I think we have to move older way instead of the navigation component. 

@ianhanniballake do you have any sample code for this issue. without a solution how you close this one.

**Comment by dalcomdev** [comment]
April, 2023. The problem still exists...
