### ISSUE TITLE
Using getValue() on LiveData returns null with Room

### ISSUE THREAD

**Issue by idragon81** [googlesamples/android-architecture-components#44]
I have a POJO set up for use with Room and retrofit

    @TypeConverters(DateConverter.class)
    @Entity(indices = {@Index("code")})
    public class HealthcareCenter {
        @PrimaryKey
        @SerializedName("id")
        private int id;
        @SerializedName("code")
        private String code;
        @SerializedName("name")
        private String name;
        @SerializedName("address")
        private String address;
        @SerializedName("phone")
        private String phone;
        @SerializedName("email")
        private String email;
        @ColumnInfo(name = "visited_date")
        @SerializedName("visited_date")
        private Date visited_date;
        ....  //Getters and setters omitted here
    }
 
And have the following method in my Dao

    @Query("select * from HealthcareCenter where code = :code")
    LiveData<HealthcareCenter> getCenterbyCode(String code);

However when using 
    
     db.healthcareCenterDao().getCenterByCode(code).getValue()
the method returns null.

As a workaround I am omitting the LiveData when I want to retrieve the value once and want to update it (Using an observer leads to a loop).

Dao
     
       @Query("select * from HealthcareCenter where code = :code")
       HealthcareCenter getNonObservableCenterbyCode(String code);
Use
    
     HealthcareCenter healthcareCenter = db.healthcareCenterDao().getNonObservableCenterbyCode(qrCode.getCenter_code());

**Comment by yigit** [comment]
don't return LiveData if you want the value sync.
LiveData is to watch the data and distribute it to the observers. It won't calculate the value until an active observer is added.

**Comment by codecameo** [comment]
This [reference](https://stackoverflow.com/questions/44428389/livedata-getvalue-returns-null-with-room/44471378#44471378) might help you.

**Comment by sssnndp** [comment]
I have added a observer in activity but still getting null in case of LiveData. and correct value when object is returned without livedata.

**Comment by jay006** [comment]
I think for the first time it returns null and when data is changed then only it returns the changed value.

**Comment by 1amGr00t** [comment]
Room is such a painful shit! I just wanna receive sync data from DB. I wouldn't be informed about updates on that data, so my functions will be called multiple times.

**Comment by yigit** [comment]
if you want to receive sync data from the DB, just use a sync query.

**Comment by 1amGr00t** [comment]
you cannot receive sync data as room does not allow on main thread

**Comment by pedrovarela86** [comment]
> you cannot receive sync data as room does not allow on main thread. .Dude!! I suggest you to read document yourself before commenting whatever, google it, buy books, do whatever but commenting shit.. thank you.

**Comment by 1amGr00t** [comment]
I guess you get me wrong. It's not my intention to load data on main thread and block the ui. I just need a single state/value from DB storage in my application without observing state changes.

**Comment by yigit** [comment]
Ok then just call room on a background thread and declare your query to return the data sync.
Why do you even try to use LiveData ?

**Comment by chaiwa-berian** [comment]
> Ok then just call room on a background thread and declare your query to return the data sync.
> Why do you even try to use LiveData ?

We would need to do a sync call to initialize the data and then observe the same LiveData for subsequent changes, just like my authentication scenario I posted on [Statckoverflow](https://stackoverflow.com/questions/54855077/getting-initial-value-for-livedata-always-returning-null). At startup I want to load the saved **token**, and then observe it as the token may be invalidated(by background sync task) or updated by the user when they log-out(logging-out doesn't delete the token as it may still be valid and can be re-used especially if the user is disconnected).

**Comment by CannibalKush** [comment]
I think that this is a completely valid use case. 

I want to sometimes just get the current values as they stand, and sometimes react to their changes.  I'm not sure whether this change would have to be at Android.Arch.LiveData or whether it would be on Room, but calling LiveData.getValue() to return a synchronous value would be great.

**Comment by vikramKirubaharan** [comment]
Room always returns Null value while using LiveData but returns proper value when we are not wrapping the value with live data. Kindly help us to resolve this. I tried inserting the new data but it is not reflecting as expected.
