### ISSUE TITLE
Upgrade Room: attempt to re-open an already-closed object: SQLiteDatabase

### ISSUE THREAD

**Issue by ChauNTM** [googlesamples/android-architecture-components#453]
I have a database, when I add a migration as below:
```
abstract class MyDatabase : RoomDatabase() {

    abstract fun dbDao(): DbDao

    companion object {
        @VisibleForTesting
        val MIGRATION_6_7: Migration = object : Migration(6, 7) {
            override fun migrate(database: SupportSQLiteDatabase) {
                MFLogger.d("MyDatabase", "MIGRATION_6_7 start")
                // I create new table and copy data from old table to new table
                ....
                MFLogger.d("MyDatabase", "MIGRATION_6_7 end")
            }
        }
    }
}
```
In "...", I create the new table and copy data from old table to new table. It works well, but sometimes I get this crash
```
PortfolioApp: uncaughtException - ex=java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.misfit.portfolio.debug/databases/589bdfade4b0ba522c4bb4dd_fitness.db
08-24 12:24:31.469 13457-13595/com.misfit.portfolio.debug W/System.err: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.misfit.portfolio.debug/databases/589bdfade4b0ba522c4bb4dd_fitness.db
08-24 12:24:31.469 13457-13457/com.misfit.portfolio.debug D/App-SplashScreenActivity: needToUpdateBLEWhenUpgradeLegacy - isNeedToUpdateBLE=false
08-24 12:24:31.469 13457-13595/com.misfit.portfolio.debug W/System.err:     at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
08-24 12:24:31.470 13457-13595/com.misfit.portfolio.debug W/System.err:     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1770)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1716)
        at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:242)
        at com.portfolio.platform.data.source.local.fitness.FitnessDatabase$Companion$MIGRATION_6_7$1.migrate(FitnessDatabase.kt:45)
        at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:85)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:133)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:259)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:96)
        at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
        at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:233)
        at com.portfolio.platform.data.source.local.fitness.FitnessDao_Impl.getPendingActivitySamples(FitnessDao_Impl.java:358)
        at com.portfolio.platform.data.source.ActivitiesRepository.pushPendingActivities(ActivitiesRepository.kt:181)
        at com.portfolio.platform.usecase.PushPendingDataUtil.start(PushPendingDataUtil.kt:32)
        at com.portfolio.platform.receiver.NetworkChangedReceiver.lambda$pushPendingData$1$NetworkChangedReceiver(NetworkChangedReceiver.java:66)
08-24 12:24:31.470 13457-13595/com.misfit.portfolio.debug W/System.err:     at com.portfolio.platform.receiver.NetworkChangedReceiver$$Lambda$0.run(Unknown Source)
```

I think this crash happened because the UI is launched and it accesses to database asynchronous with starting migration. Did anyone meet the same problem like this?

**Comment by guger** [comment]
@ChauNTM did you solve the problem?

**Comment by pedrovarela86** [comment]
Update DB version

**Comment by guger** [comment]
@pedrovarela86 Already tried this... Does room ensure, that there are no async queries before migration is done?

**Comment by pedrovarela86** [comment]
Do you have .fallbackToDestructiveMigration()? 

Allows Room to destructively recreate database tables if Migrations that would migrate old database schemas to the latest schema version are not found.
When the database version on the device does not match the latest schema version, Room runs necessary Migrations on the database.
If it cannot find the set of Migrations that will bring the database to the current version, it will throw an IllegalStateException.
You can call this method to change this behavior to re-create the database instead of crashing.
Note that this will delete all of the data in the database tables managed by Room

**Comment by guger** [comment]
@pedrovarela86 No, but I provide a Migration from Version 1 to 2...
The app crashes at the first "database" call of my Migrations' migrate method.

**Comment by pedrovarela86** [comment]
@guger well, nothing else comes to my mind, maybe an updated version of room? Are you using android x? sorry I can't help further.

**Comment by svyatoslavpavlov** [comment]
I have same problem, use android.arch.persistence.room 1.1.1

**Comment by guger** [comment]
@pedrovarela86 I'm using Room (AndroidX) version 2.0.0...
Is it possible that this error is caused by async query access during migration?

**Comment by BartNijland91** [comment]
Having the exact same problem. Only way I can think of fixing it is providing a callback myself when the migration is finished and only let the app continue when it's done.

**Comment by guger** [comment]
@BartNijland91 I just found an article, describing the migration process of room:

1. The Room database is built
2. SQLiteOpenHelper.onUpgrade method is called and Room triggers the migrations
3. The database is opened
(https://medium.com/androiddevelopers/understanding-migrations-with-room-f01e04b07929)

If this is true, it cannot be that any object accesses the database before migration is finished.. So obviosly, this is not the problem?

Did you already try implementing a callback? Did it work?

**Comment by BartNijland91** [comment]
@guger Yes it works like that! The problem I'm having is that on app startup I do multiple queries in multiple background threads, so the migration process is ran async with queries. This will fail because room will try to get the database while it's doing the migration.

**Comment by drayan85** [comment]
@BartNijland91, I have implementedted Room first time in our Android App before we were using `SQLiteOpenHelper`. I have implemented migration and facing the same issue. App start-up calling multiple queries from different background threads and causing `java.lang.IllegalStateException: attempt to re-open an already-closed object` crashing the app.
Have you find any way to handle this situation ?

**Comment by neworld** [comment]
@BartNijland91, how it is possible? I checked code in room `2.1.0-alpha03`, and found, all database getters are syncronized:
```java
        synchronized SupportSQLiteDatabase getWritableSupportDatabase() {
            mMigrated = false;
            SQLiteDatabase db = super.getWritableDatabase();
            if (mMigrated) {
                // there might be a connection w/ stale structure, we should re-open.
                close();
                return getWritableSupportDatabase();
            }
            return getWrappedDb(db);
        }

        synchronized SupportSQLiteDatabase getReadableSupportDatabase() {
            mMigrated = false;
            SQLiteDatabase db = super.getReadableDatabase();
            if (mMigrated) {
                // there might be a connection w/ stale structure, we should re-open.
                close();
                return getReadableSupportDatabase();
            }
            return getWrappedDb(db);
        }
```

AFAIK, there is no way two threads could process migration. Also `close()` is syncronized as well. Maybe I am missing something?

@guger, maybe do you remember more details about `The error was caused by another crash shortly before, which closed the db.`? How do you hunt it down? Thanks in advance!

**Comment by guger** [comment]
@neworld I found the error because I noticed two error events in my crashlytics console. But if the db crashes with 'attempt to reopen an already closed object' because of an previously thrown error, you'll find two error logs in the Logcat.
Keep in mind, that this error is maybe not visible in the log of the 'Run'-window of Android Studio, it is only visible in the Logcat.

**Comment by vincent-paing** [comment]
Has anyone figured out a way to resolve this?

**Comment by guger** [comment]
@vincent-paing I think this error is a follow-up event of a previous error. The problem is not room, but your individual code. This was the problem in my case. I'd an issue inserting some items, which crashed the db. This error was the result of the issue above.

**Comment by neworld** [comment]
Older version [handled incorrectly corrupted databses](https://issuetracker.google.com/issues/124476912). You could try an upgraded one. Also, in my case database corrupted due to out-of-disk space. It was my bad, not room.

**Comment by jonneymendoza** [comment]
Has anyone resolved this yet?

**Comment by radityagumay** [comment]
> @BartNijland91 I just found an article, describing the migration process of room:
> 
> 1. The Room database is built
> 2. SQLiteOpenHelper.onUpgrade method is called and Room triggers the migrations
> 3. The database is opened
>    (https://medium.com/androiddevelopers/understanding-migrations-with-room-f01e04b07929)
> 
> If this is true, it cannot be that any object accesses the database before migration is finished.. So obviosly, this is not the problem?
> 
> Did you already try implementing a callback? Did it work?
> 
> **EDIT:**
> I've solved my problem. The error was caused by another crash shortly before, which closed the db.

what crash?

**Comment by hasnafoundation** [comment]
We are facing the same issue, if anyone comes with any solution then please post here.

**Comment by nickyrabit** [comment]
> Update DB version

I always forget this and you always remind me

**Comment by XWZack** [comment]
I had the exactly same problem, the thing is , my SQL sentence is wrong, not room.

**Comment by salihuumar75** [comment]
upgrade your room version and it will fix it for you

**Comment by radityagumay** [comment]
> upgrade your room version and it will fix it for you

@salihuumar75 is there any reference from your statement?
