### ISSUE TITLE
MVP Sample

### ISSUE THREAD

**Issue by omar25h** [googlesamples/android-architecture-components#46]
Hi,
I would like to know if there are any plans to add an MVP sample to the repository. Thanks in advance!

**Comment by JoseAlcerreca** [comment]
No plans. What components would you like to see? 

ViewModels could be used to act as presenters, but they need a view reference which is almost the whole point of ViewModels (to not have the reference).

LiveData is an observable to make UIs reactive, so basically the opposite of what presenters do.

If you mean Room, then we have one:

https://github.com/googlesamples/android-architecture/tree/dev-todo-mvp-room/

**Comment by omar25h** [comment]
Oh alright then. Thanks for the explanation

**Comment by thomasdsouza** [comment]
@JoseAlcerreca ... In https://developer.android.com/topic/libraries/architecture/lifecycle.html
"If your UI is complex, consider creating a Presenter class to handle UI modifications. This is usually overkill, but might make your UIs easier to test."
If we were to choose not to use databinding, how would we use ViewModel, LiveData if we don't use Presenters? Kindly advise.

**Comment by badarshahzad** [comment]
This link is not working https://github.com/googlesamples/android-architecture/tree/dev-todo-mvp-room/
