### ISSUE TITLE
[PagingWithNetworkSample] If there is change in local database room

### ISSUE THREAD

**Issue by antranvn** [googlesamples/android-architecture-components#471]
Hi there, if there any change in local database room, how can the UI update its change? Or where can i find information about ui live update in this sample

Currently, in my fragment, i observe LiveData<PagedList<T>> which also have boundary callback, but when i edit my room database, the ui is not update.

**Comment by ChrisCraik** [comment]
The boundaryCallback fires when the user scrolls to either end of the list.

If you independently edit the room database, you should see the UI update - see for example the PagingSample (the one with no network). Editing the local database updates the UI (though note it is asynchronous).

**Comment by antranvn** [comment]
Thank you @ChrisCraik . I can see the update by updating database by Dao instead of manually edit table.
