### ISSUE TITLE
a question about Paging

### ISSUE THREAD

**Issue by shaomaicheng** [googlesamples/android-architecture-components#473]
hi， I use paging to load my data. it work normal every page. But I have a question, when  I  change mylist  item 's data, what should I do?

class PagedList do not have any API to set new obejct by position
it's set method is 
```
public E set(int index, E element) {
        throw new UnsupportedOperationException();
    }
```

**Comment by guger** [comment]
@shaomaicheng It is not necessary to insert an item at a specific position with paging as far as I know. The library itself checks for the changed items in the list and appropriately animates e.g. the recyclerview. (Therefore you've implemented the `DiffUtil.ItemCallback`.

**Comment by shaomaicheng** [comment]
i just modify adapter.getitem 's result and notify this item index to refresh and it work normal.....but .I do not add any code?   i do no know what happen....
