### ISSUE TITLE
How to handle permission requests to operation in view model?

### ISSUE THREAD

**Issue by luna-vulpo** [googlesamples/android-architecture-components#48]
In my view I have button which start recording audio I want to ask user to grant permission when user click on the button. 
For example: How to ask  permission for fine localization in BasicExample?

**Comment by yigit** [comment]
@mynote +1. OS interactions needs to stay in the activity / fragment.

**Comment by deviant-studio** [comment]
how about true mvvm (which many of us trying to build on top of databindings lib)? the ui event handlers are part of view model there.
