### ISSUE TITLE
create custom PagedList.BoundaryCallback

### ISSUE THREAD

**Issue by ahmed56734** [googlesamples/android-architecture-components#481]
I need to implement a recycler view that loads more data from the bottom and from the top
but that boundary callback have function loadAfter() only that triggered when user reaches the recycler view end
is it possible to customize it so we can load when he reaches the top of the recycler view

**Comment by ChrisCraik** [comment]
Are you talking about BoundaryCallback (used for paging data from network to disk), or DataSource (used for paging data into memory)?

Both of these have the ability to load more data above - see BoundaryCallback.onItemAtFrontLoaded(), or ItemKeyedDataSource.loadBefore. Are either of those what you're looking for?

**Comment by ahmed56734** [comment]
I think BoundaryCallback.onItemAtFrontLoaded() could be what I am looking for,
I didn't know it exists
