### ISSUE TITLE
In Kotlin, when a Room column field begins with 'is_', build fails saying "Cannot find setter for field"

### ISSUE THREAD

**Issue by Javi** [googlesamples/android-architecture-components#49]
An example would be 
` @Entity
  class Foo {
    @ColumnInfo
    var is_bar: Boolean = false
  }`

**Comment by yigit** [comment]
hmm i wonder what kotlin generates. Did you try accessing it from java? what is the setter/getter that kotlin generates?

**Comment by yigit** [comment]
btw, please use the issue tracker for bugs. (https://issuetracker.google.com).

**Comment by jutikorn** [comment]
I think '**is**' is a specific keyword for SQLite which couldn't be used as table column.
http://www.sqlite.org/lang_keywords.html

**Comment by mochadwi** [comment]
> I think '**is**' is a specific keyword for SQLite which couldn't be used as table column.
> http://www.sqlite.org/lang_keywords.html

I think it depends on our problem, if persist you can check this list:

- https://inneka.com/programming/android/cannot-find-setter-for-field-using-kotlin-with-room-database/
- https://www.coroutinedispatcher.com/2019/08/solving-room-cannot-find-setter-for.html
