### ISSUE TITLE
Attempt to re-open an already-closed object

### ISSUE THREAD

**Issue by DmitrySoloviyev** [googlesamples/android-architecture-components#500]
After i added an migration with `database.execSQL("ALTER TABLE `users` ADD COLUMN status_id INTEGER NOT NULL DEFAULT 0");` text i've found this exception. I think it's because getUserName() in UserActivity.class called in Schedulers.io(). How to solve it?

**Comment by guger** [comment]
You've two spaces at after TABLE and before ADD?

**Comment by ianhanniballake** [comment]
Please file issues with Room on the [issue tracker](https://issuetracker.google.com/issues/new?component=413107) with a sample project that reproduces your issue.
