### ISSUE TITLE
NavigationBasicSample  regards pop fragment

### ISSUE THREAD

**Issue by sathishmscict** [googlesamples/android-architecture-components#505]
Reporting an issue with the Architecture Components or the samples?
NavigationBasicSample 

## Question about Architecture Components? 
During pop  to fragement everytime recreated

## Bug report or feature request for Architecture Components? 
During fragment navigation navigate A screen to B screen.and pop to A screen entire fragment recreated. Anyway how to resume fragment once it is loaded on container.Edittext values are retained but api calls not retained because everytime fragment recreated.

**Comment by ianhanniballake** [comment]
You can use a [ViewModel](https://developer.android.com/topic/libraries/architecture/viewmodel) to retain data over configuration changes and while on the back stack.
