### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 343, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it

### ISSUE THREAD

**Issue by iantomemortel** [googlesamples/android-architecture-components#518]
Reporting an issue with the Room Library

I had this weird crash issue for the first time, and I couldn't reproduce it anymore.

**This is my entity:**
`@Entity
public class PropertyV2 {
    @NonNull
    @PrimaryKey
    public String id;
    public String basic_baths;
    public String basic_beds;
    public String area;
    public String basic_date_added_on_swoop;
    public String basic_description;
    public String basic_featured_static_image_cloudinary;
    public String basic_featured_static_image_downloadURL;
    public String basic_location_address;
    public String basic_location_city_province;
    public String basic_location_house_no_street;
    public String basic_location_lat;
    public String basic_location_lng;
    public String basic_price;
    public String basic_size;
    public String basic_status;
    public String basic_type;
    public String details_condition;
    public String details_developer;
    public String details_property_name;
    public String details_property_type;
    public Boolean is_pd_inserted = false;

    @Embedded
    public PropertyV2Details property_details;

    public PropertyV2() {
    }

    public PropertyV2Details getProperty_details() {
        return property_details;
    }

    public void setProperty_details(PropertyV2Details property_details) {
        this.property_details = property_details;
    }
}`

**This is my DAO class;**
`@Dao
@TypeConverters(ListTypeConverter.class)
public interface PropertyV2Dao {
    @Query("select * from PropertyV2")
    LiveData<List<PropertyV2>> loadAllProperties();

    @Query("select * from PropertyV2 where id = :id")
    LiveData<PropertyV2> loadProperty(String id);

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    List<Long> insertAll(List<PropertyV2> properties);

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    Long insert(PropertyV2 property);

    @Delete
    void deteProperties(List<PropertyV2> properties);

    @Query("DELETE FROM PropertyV2")
    void nukeTable();

    @Update
    void updateProperty(PropertyV2 propertyV2);
}
`

**And here's the stack trace:**

Fatal Exception: java.lang.IllegalStateException: Couldn't read row 343, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetString(CursorWindow.java)
       at android.database.CursorWindow.getString(CursorWindow.java:438)
       at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
       at projectassistant.swoop.data.local.db.dao.PropertyV2Dao_Impl$5.compute(PropertyV2Dao_Impl.java:1340)
       at projectassistant.swoop.data.local.db.dao.PropertyV2Dao_Impl$5.compute(PropertyV2Dao_Impl.java:1128)
       at android.arch.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:100)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Additional info:**
The app's  main feature is to search properties(i.e condominium, apartment) and show them to the user. Every time a user makes a new search, I basically deleted the old data from the local database and insert the new ones based on the user's latest search results. I use a repository class that directly communicates with the DAOs to insert, delete and update my data to or from the database. I use asynctask to insert new data to the database, but before I insert the data, I have to nuke the table first to delete the old data. I also use mediator live data for reading data changes from the database.

**Comment by msyulw** [comment]
same issue here. Is there a fix for this?

**Comment by ianhanniballake** [comment]
Please file issues with Room on the [issue tracker](https://issuetracker.google.com/issues/new?component=413107) with a sample project that reproduces your issue.

**Comment by RealDevAy** [comment]
I think this is an issue with older devices. I am already having this issue and it only happens on older devices with low memory.

**Comment by conde-aruns** [comment]
is this issue fixed? I am stilling facing this issue
Its happening for android version 11, 12, 13, and 14 as well.
