### ISSUE TITLE
Support for Kotlin sealed classes in Room

### ISSUE THREAD

**Issue by abhaysood** [googlesamples/android-architecture-components#52]
Kotlin's sealed classes are awesome. But as they do not have public constructors, I guess there is little chance of supporting them with Room. Any thoughts on this?

**Comment by yigit** [comment]
yea, if Room cannot construct them, it cannot use it.
We actually generate code in the same package but i'm not sure what Kotlin does w/ sealed classes.

**Comment by abhaysood** [comment]
I was trying to dig into sealed classes to see what happens under the hood. Putting it here for anyone else who might be trying the same.

If we have a sealed class like the following:
```
sealed class Sealed {
  data class DATA_CLASS(val value: String): Sealed()
}
```

Kotlin converts the above to two classes on compilation: `Sealed.class` and `Sealed$DATA_CLASS.class`:


Here's what `javap -p -c Sealed.class` spits out:

```
public abstract class Sealed {
  private Sealed();
    Code:
       0: aload_0
       1: invokespecial #8                  // Method java/lang/Object."<init>":()V
       4: return

  public Sealed(kotlin.jvm.internal.DefaultConstructorMarker);
    Code:
       0: aload_0
       1: invokespecial #12                 // Method "<init>":()V
       4: return
}
```

[kotlin_sealed_class.zip](https://github.com/googlesamples/android-architecture-components/files/1066298/kotlin_sealed_class.zip)

**Comment by tomaszpolanski** [comment]
Sealed classes are normal classes with the abstract superclass. 
They have public constructors so Room should be able to create them.

This sealed class:
```
sealed class Animal {
    abstract val age: Int

    class Dog(override val age: Int) : Animal()
    class Spider(override val age: Int) : Animal()
}
```

Would resolve to this in Java:
```
public abstract class Animal {
    public abstract int getAge();

    private Animal() {
    }
    public static final class Dog extends Animal {
        private final int age;

        public int getAge() {
            return this.age;
        }

        public Dog(int age) {
            this.age = age;
        }
    }

    public static final class Spider extends Animal {
        private final int age;

        public int getAge() {
            return this.age;
        }

        public Spider(int age) {
            this.age = age;
        }
    }
}
```

If Room handles abstract classes, there should not be a problem to handle sealed classes from kotlin.
Having Room support sealed classes would be a great improvement and kotlin users would really appriciate it!

**Comment by aromano272** [comment]
I stumbled across this while searching about kotlin sealed classes, so I though I'd comment with a working solution:

`
sealed class SealedEntity(
    @Ignore open val data: String?
) {

    @PrimaryKey(autoGenerate = true)
    var id: Int = 0

    @Entity
    data class One(override val data: String?) : SealedEntity(data)

    @Entity
    data class Two(override val data: String?) : SealedEntity(data)

    @Entity
    data class Three(override val data: String?) : SealedEntity(data)

}
`

**Comment by Binghammer** [comment]
@aromano272 Careful with this. `id` is not considered in the generated `hashCode` and `equals` functions. Data classes only include direct properties. So technically this is true

```
val oneA = SealedEntity.One(shared = "baz", uniqueA = "foobar")
oneA.id = 1
val oneB = SealedEntity.One(shared = "baz", uniqueA = "foobar")
oneB.id = 5
assertEquals(oneA, oneB) //true, even though ids are different
```

Personally, I would make `id` abstract. Simply because one may think that it is hashed where it is a data class.

**Comment by Pyol7** [comment]
Is there any way to make the sealed class (SealedEntity) the @Entity? That way all the child classes can be stored in the same table.
