### ISSUE TITLE
Room and LiveData

### ISSUE THREAD

**Issue by mofada** [googlesamples/android-architecture-components#520]
I used Room+Livedata, but I have some questions. In the conditional query, how do I update the conditions in real time, such as if I need to search?

@Query("select * from NotebookBean where title like :title ")
Fun query(title:String): LiveData<List<NotebookBean>>

How do I query the database when the search box changes?

**Comment by amalhanaja** [comment]
just perform query again when on search query change

**Comment by mofada** [comment]
> 在搜索查询更改时再次执行查询

Suppose I have an observer to receive the observation result, but if I query again, the observer will observe the results of the two queries, and there will be problems. The solution I think of is to cancel the previous one, and then observe the current one, but I think this is not the case. Very good, so ask the official recommendation

**Comment by murageden** [comment]
@amalhanaja's way will work if you should observe on the LiveData<List>. This way you will get the results only when there is changes on the LiveData<List> of which the change will come as a result of the query params changing.

**Comment by mofada** [comment]
@angusholder Thank you, I think this is the best way to achieve it, but what if I have multiple parameters, suppose I have a page (page number) and title (search content title), what should I do at this time?

**Comment by murageden** [comment]
Cool
