### ISSUE TITLE
Reporting an issue with the Architecture Components

### ISSUE THREAD

**Issue by ananthramasamy** [googlesamples/android-architecture-components#522]
## Question about Architecture Components-Navigation? 
1.Navigation Architecture Component - how to set/change custom back or hamburger icon with navigation controller?

2.Using NavigationView

**Comment by ianhanniballake** [comment]
I'd encourage you to [look through the official issue tracker[(https://issuetracker.google.com/issues?q=componentid:409828) to see if your feature request is already submitted or file a feature request / documentation request.
