### ISSUE TITLE
Navigation [DESTINATION_NAME]  is unknown to this navController after calling navigateUp in Observer

### ISSUE THREAD

**Issue by RizkyArifNur** [googlesamples/android-architecture-components#532]
I have 3 fragments = Fragment A, Fragment B, and Fragment C

now I'm on Fragment B, I try to move back to the previous fragment which is Fragment A and call `Navigation.findNavController(view).navigateUp()` from Observer ViewModel and after that, I try to move to another fragment which is Fragment C and call  `Navigation.findNavController(view).navigate(R.id.fragment_c)` but I get an error `Navigation [DESTINATION_NAME]  is unknown to this navController` and the app was force closed

Here is my code 
`viewModel.dataUpdateBackend.observe(this, Observer {
          isSuccessful ->  if (isSuccessful){
                Toast.makeText(context, activity?.getString(R.string.toast_data_berhasil_dikirim), Toast.LENGTH_LONG).show()
Navigation.findNavController(imageView_arrowBack).navigateUp()
            }
        })`

**Comment by ianhanniballake** [comment]
Please file Navigation library bugs on the [issue tracker](https://issuetracker.google.com/issues/new?component=409828) with a sample project that reproduces your issue.

**Comment by nguyenvanminhfptpoly** [comment]
add throwable in subscribe method

``
 itemAdapter.observeClickListener().subscribe ({
            bundle.putSerializable("ui",it)
            view?.findNavController()?.navigate(R.id.action_uiFragment_to_detailFragment, bundle)
        },{
            t ->
            t.message?.let { onError(it) }
        }).addTo(compositeDisposable)
``
