### ISSUE TITLE
[Navigation Component] I can`t change animation from NavigationUI.setupWithNavController()

### ISSUE THREAD

**Issue by minshoki** [googlesamples/android-architecture-components#537]
call `NavigationUI.setupWithNavController(bottomNavigationView, navController)` 
default fade in/out animation.

But, I want remove animation or change animation.

help me.

**Comment by STAR-ZERO** [comment]
Add anim default files, you can change animation.

- res/anim/nav_default_enter_anim.xml
- res/anim/nav_default_exit_anim.xml
- res/anim/nav_default_pop_enter_anim.xml
- res/anim/nav_default_pop_exit_anim.xml

Like a below, disable animation.

```xml
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
</set>
```

Ref: https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/navigation/ui/src/main/res/anim/

**Comment by Mr-Ramzan** [comment]
Facing similar issues fragment transitions are not working while setup with bottom navigation.
I have used custom XML resources for animations as well but no use.
I have setup nave controller with bottom navigation as documented added enter and exit transitions by clicking arrows.
Can anyone please help.

**Comment by farislr** [comment]
> Add anim default files, you can change animation.
> 
> * res/anim/nav_default_enter_anim.xml
> * res/anim/nav_default_exit_anim.xml
> * res/anim/nav_default_pop_enter_anim.xml
> * res/anim/nav_default_pop_exit_anim.xml
> 
> Like a below, disable animation.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <set xmlns:android="http://schemas.android.com/apk/res/android">
> </set>
> ```
> 
> Ref: https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/navigation/ui/src/main/res/anim/

I tried this but it doesn't work. 

And then I changed the _anim_ resource folder to _animator_. This should fix them.
I think they use @animator as a default animation resource folder.
