### ISSUE TITLE
[Question] Viewmodel with Databinding  and ViewPager

### ISSUE THREAD

**Issue by daimonkor** [googlesamples/android-architecture-components#54]
Please help, I have viewpager with fragments, databinding into viewmodel. Where I need use setCurrentItem and add functions of viewpager's adapter (view or viewmodel-databinding)? Is it necessary to create viewmodel for every viewpager's item? 
Thanks for help.

**Comment by yigit** [comment]
It depends on your use case but it is probably good idea for each fragment to have its own view model.
