### ISSUE TITLE
How to show list not from start?

### ISSUE THREAD

**Issue by Anton111111** [googlesamples/android-architecture-components#572]
Hi! I have in db 100 items. And I want show list from item number 20 instead of first. How can I do it?

**Comment by adrian110288** [comment]
Use raw SQL statement with OFFSET clause. See [https://www.petefreitag.com/item/451.cfm](url)

**Comment by Anton111111** [comment]
> Use raw SQL statement with OFFSET clause. See [https://www.petefreitag.com/item/451.cfm](url)

Link don't works. And i don't understand ;) Can i use datasource that return Room?
To clear task. I need show list from item number 20. But user can scroll to first item and scroll to last item. I need show the list that contain all items from db but i need start show list from set position

**Comment by JoseAlcerreca** [comment]
Unrelated to samples. Try SO.
