### ISSUE TITLE
Immuniweb security issue

### ISSUE THREAD

**Issue by sathishmscict** [googlesamples/android-architecture-components#584]
## Question about Architecture Components? 
Room database  : 
implementation "android.arch.persistence.room:runtime:1.1.1"

* Questions about the Room library: android-room 
https://stackoverflow.com/questions/55136032/room-database-security-vulnerability-issue

## Bug report or feature request for Architecture Components? 

 have found 1 security issue in Room database.
https://www.htbridge.com

![image](https://user-images.githubusercontent.com/18158746/54259307-50360900-458b-11e9-9289-3bf6cde5af25.png)

**Comment by JoseAlcerreca** [comment]
Unrelated to samples, please report on the component's issue tracker.

**Comment by sathishmscict** [comment]
Can you please send link/url

**Comment by sathishmscict** [comment]
> Unrelated to samples, please report on the component's issue tracker.

Can you please send link/url

**Comment by JoseAlcerreca** [comment]
The template for a new issue has all the links
https://github.com/googlesamples/android-architecture-components/issues/new
