### ISSUE TITLE
How to use global action if the sample use 3 navigation graphs?

### ISSUE THREAD

**Issue by deckyfx** [googlesamples/android-architecture-components#599]
How to use global action if the sample use 3 navigation graphs?

**Comment by hossein-amini** [comment]
I have same issue, did you fix it?

**Comment by deckyfx** [comment]
Well.... yes and no.

There is no real global action, that could work for all navgraph files, 
so for example in my case, to navigate to common dialog fragment, i put it in another navigraph file, 
then all other navgraph files should include it and make action to the included navgraph

**Comment by li2** [comment]
But that means duplicated nested graph and duplicated args if needed. Since the common fragments (dialog or webview) are really essential, and duplicated is not so good. Are there any better solutions?

**Comment by deckyfx** [comment]
Yeah not best solution, and i even caught on cyclic nav graph include crash because of this, need better solution

**Comment by L4grange** [comment]
I'm also facing this problem, but in my use case the 3 out of 5 tabs that I need are the same fragment, so I cannot use different nav graphs. Is there a way to use the same nav graph for all the tabs of the bottom navigation but still have different back stacks?

I'm close to a point of dropping the Navigation Component altogether, I don't think it's made to handle complex navigation cases.

**Comment by tommos23** [comment]
@deckyfx How did you solve the cyclic nav graph include crash?

**Comment by sinhpn92** [comment]
Hummm... I am looking for the better solution too. Did anyone solve it?

**Comment by L4grange** [comment]
I've ended up creating 3 of the same fragment (that point to the same class) as destinations in my Nav Graph where each one of them gets the different params I need. Not the cleanest solution, but it works for now.

**Comment by AlexSheva-mason** [comment]
I also encountered this issue and was looking for a solution, stumbled upon this SO answer 

https://stackoverflow.com/questions/62591099/using-global-actions-with-multiple-graphs-in-jetpack-navigation

I wonder if that's the only reasonable solution for today?

**Comment by Njuacha** [comment]
Let me show you with an example 


    <navigation ...
      app:startDestination:"@id/nav_graph_one">
   
      <include app:graph:"@navigation/nav_graph_one"/>
      <include app:graph:"@navigation/nav_graph_two"/>
      <include app:graph:"@navigation/nav_graph_three"/>

      <fragment
         android:id="@+id/aCommonFragment"
         .../>
      <action
         android:id="@+id/action_grobal_aCommonFragment
         app:destination="@+id/aCommonFragment"/>
    </navigation>

Any where from you app you can now use 

     findNavigationController.navigate(NavGraphDirections.actionGlobalACommonFragment)
