### ISSUE TITLE
Question: Does Room support multithreaded insert (and is it thread-safe if not)?

### ISSUE THREAD

**Issue by gajicm93** [googlesamples/android-architecture-components#60]
Essentially, does Room support multithreaded insert, or is it atleast internally synchronized, so I don't run into some kind of Concurrent Modification exception?

I see that you use a single-thread Executor for IO in the samples, so is it necessary, or Room takes care of it itself?

Thanks!

**Comment by yigit** [comment]
Database takes care of itself so you should not need to worry. Room creates a transaction for each modification automatically. You need to be careful though not to deadlock yourself with your other threads.

**Comment by song314** [comment]
Nice question & Nice ROOM
