### ISSUE TITLE
Room query with three or more IN query parameter has code generation issue

### ISSUE THREAD

**Issue by kpbird** [googlesamples/android-architecture-components#61]
Room will generate DAO based on annotation

If @Quary has three or more IN query parameters then DAO code generation has error.

For example. Below query has three in query parameters ids, price and type.

@Query("select * from products where name like :query and id in (:ids) and price in (:price) and type in (:type)")
    LiveData<List<ProductEntity>> searchProducts(String query,int[] ids,int[] price,int[] type);

**Error**

Error:(258, 31) error: ';' expected
Error:(258, 36) error: not a statement
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Code Generated**
Error in _argIndex = 2 + _inputSize,  + _inputSize_1;

 @Override
  public LiveData<List<ProductEntity>> searchProducts(String query, int[] ids, int[] price,
      int[] type) {
    StringBuilder _stringBuilder = StringUtil.newStringBuilder();
    _stringBuilder.append("select * from products where name like ");
    _stringBuilder.append("?");
    _stringBuilder.append(" and id in (");
    final int _inputSize = ids.length;
    StringUtil.appendPlaceholders(_stringBuilder, _inputSize);
    _stringBuilder.append(") and price in (");
    final int _inputSize_1 = price.length;
    StringUtil.appendPlaceholders(_stringBuilder, _inputSize_1);
    _stringBuilder.append(") and type in (");
    final int _inputSize_2 = type.length;
    StringUtil.appendPlaceholders(_stringBuilder, _inputSize_2);
    _stringBuilder.append(")");
    final String _sql = _stringBuilder.toString();
    final int _argCount = 1 + _inputSize + _inputSize_1 + _inputSize_2;
    final RoomSQLiteQuery _statement = RoomSQLiteQuery.acquire(_sql, _argCount);
    int _argIndex = 1;
    if (query == null) {
      _statement.bindNull(_argIndex);
    } else {
      _statement.bindString(_argIndex, query);
    }
    _argIndex = 2;
    for (int _item : ids) {
      _statement.bindLong(_argIndex, _item);
      _argIndex ++;
    }
    _argIndex = 2 + _inputSize;
    for (int _item_1 : price) {
      _statement.bindLong(_argIndex, _item_1);
      _argIndex ++;
    }
#     **_argIndex = 2 + _inputSize,  + _inputSize_1;**
    for (int _item_2 : type) {
      _statement.bindLong(_argIndex, _item_2);
      _argIndex ++;
    }
    return new ComputableLiveData<List<ProductEntity>>() {
      private Observer _observer;

      @Override
      protected List<ProductEntity> compute() {
        if (_observer == null) {
          _observer = new Observer("products") {
            @Override
            public void onInvalidated() {
              invalidate();
            }
          };
          __db.getInvalidationTracker().addWeakObserver(_observer);
        }
        final Cursor _cursor = __db.query(_statement);
        try {
          final int _cursorIndexOfId = _cursor.getColumnIndexOrThrow("id");
          final int _cursorIndexOfName = _cursor.getColumnIndexOrThrow("name");
          final int _cursorIndexOfDescription = _cursor.getColumnIndexOrThrow("description");
          final int _cursorIndexOfPrice = _cursor.getColumnIndexOrThrow("price");
          final int _cursorIndexOfType = _cursor.getColumnIndexOrThrow("type");
          final List<ProductEntity> _result = new ArrayList<ProductEntity>(_cursor.getCount());
          while(_cursor.moveToNext()) {
            final ProductEntity _item_3;
            _item_3 = new ProductEntity();
            final int _tmpId;
            _tmpId = _cursor.getInt(_cursorIndexOfId);
            _item_3.setId(_tmpId);
            final String _tmpName;
            _tmpName = _cursor.getString(_cursorIndexOfName);
            _item_3.setName(_tmpName);
            final String _tmpDescription;
            _tmpDescription = _cursor.getString(_cursorIndexOfDescription);
            _item_3.setDescription(_tmpDescription);
            final int _tmpPrice;
            _tmpPrice = _cursor.getInt(_cursorIndexOfPrice);
            _item_3.setPrice(_tmpPrice);
            final int _tmpType;
            _tmpType = _cursor.getInt(_cursorIndexOfType);
            _item_3.setType(_tmpType);
            _result.add(_item_3);
          }
          return _result;
        } finally {
          _cursor.close();
        }
      }

      @Override
      protected void finalize() {
        _statement.release();
      }
    }.getLiveData();
  }

**Comment by JoseAlcerreca** [comment]
Please report issues that are not related to samples in
https://issuetracker.google.com/issues/new?component=197448&template=878802

Thank you!

**Comment by kpbird** [comment]
Issue reported in the issue tracker. Thank You
