### ISSUE TITLE
NavigationAdvancedSample - navigate to new fragment without BottomNavigationView below

### ISSUE THREAD

**Issue by antranvn** [googlesamples/android-architecture-components#638]
Is it possible to navigate from a fragment which with BotomNavigationView to another fragment without BottomNavigationView?

**Comment by Podox2** [comment]
How did you achieve this? Obviously you should show/hide bottom bar in Activity. But how to get current fragment in proper way?

**Comment by CQBOBOZHU** [comment]
navController.addOnDestinationChangedListener { controller,
                                                        destination,
                                                        arguments ->
          
            if (destination.id == R.id.titleScreen || destination.id == R.id.leaderboard || destination.id == R.id.register) {
                bottomNavigationView.visibility = View.VISIBLE
            } else {
                bottomNavigationView.visibility = View.GONE
            }

        }

i do this
