### ISSUE TITLE
Can't import project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-architecture-components#647]
I get this:

![image](https://user-images.githubusercontent.com/5357526/58382299-53109980-7fd1-11e9-8be1-340bc513bca6.png)

Android Studio 3.5 Beta 1
Build #AI-191.6707.61.35.5529924, built on May 3, 2019
JRE: 1.8.0_202-release-1483-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by JoseAlcerreca** [comment]
Open one of the directories inside instead of the root. It's not one big project but multiple projects.

**Comment by ashraf-patel** [comment]
@JoseAlcerreca is there any better way to do that? opening the single directory works but what if we need to navigate between directories?

**Comment by JoseAlcerreca** [comment]
You can open two instances of Android Studio.

**Comment by AndroidDeveloperLB** [comment]
Why can't we open multiple at the same time?
I need to open one after another...
