### ISSUE TITLE
What means 'vo' package name ? 

### ISSUE THREAD

**Issue by juanpmarin** [googlesamples/android-architecture-components#65]
Thanks !

**Comment by oldergod** [comment]
[Value object](https://en.wikipedia.org/wiki/Value_object).

**Comment by juanpmarin** [comment]
Great, thanks !

**Comment by starkej2** [comment]
I was wondering the same thing. It's a pretty obscure package name for a sample project.

**Comment by kujaomega** [comment]
Wouldn't It be better to rename It to valueObject?
