### ISSUE TITLE
Using NavigationController Does this class have a memory leak?

### ISSUE THREAD

**Issue by chenycu** [googlesamples/android-architecture-components#66]
In the GithubBrowserSample project, the use of the NavigationController this class, when the Activity / Fragment destroyed, NavigationController variable in the fragmentManager also hold the Activity reference, which does not leak on the memory?

> public class NavigationController {   
    private final int containerId;
    private final FragmentManager fragmentManager;
    @Inject
    public NavigationController(MainActivity mainActivity) {
        this.containerId = R.id.container;
        this.fragmentManager = mainActivity.getSupportFragmentManager();
    }

**Comment by ipgaero** [comment]
there`s no leaks. Checke profiler, there`s only one instance at the time even if you change configuration. it seems like at this case NavigationController  gets link to fragmentManager  not to MainActivity
