### ISSUE TITLE
Cant‘t find any runnable module after pull the whole project and build

### ISSUE THREAD

**Issue by zlilover** [googlesamples/android-architecture-components#684]
how can i config this project?

**Comment by dlam** [comment]
I'm not really sure what state your setup is in, but each folder in root dir of this repo is a separate project.

If you cd into PagingWithNetwork for example and run `./gradlew tasks` what happens?

**Comment by zlilover** [comment]
thanks a lot，i have imported each module as a separate project while i wanted to import all of them in one project at first
