### ISSUE TITLE
How can i use dependency injection with shared ViewModel

### ISSUE THREAD

**Issue by AsadLeo14** [googlesamples/android-architecture-components#689]
Using injected viewmodel from activity how can i be able to use it as sharedviewmodel amongst fragments.

**Comment by pratz9999** [comment]
@AsadLeo14 did you find the answer?

**Comment by AsadLeo14** [comment]
> @AsadLeo14 did you find the answer?

Yes! you can inject viewmodel factory  and pass it to ViewModelProviders just like:

```
 @Inject
    lateinit var viewModelFactory: ViewModelProvider.Factory
   private val viewModel : YourViewModel by activityViewModels{ viewModelFactory }

```

**Comment by pratz9999** [comment]
@AsadLeo14 Thank, It worked like charm.
