### ISSUE TITLE
Room database version upgrade, with fallbackToDestructiveMigration() but still get exception

### ISSUE THREAD

**Issue by lannyf77** [googlesamples/android-architecture-components#696]
Having database of version 1,

    @Database(entities = [
      ArticleEntity::class,
      VideoEntity::class,
      ImageEntity::class,
      ItemEntity::class,
      TimestampEntity::class
    ], version = 1, exportSchema = true)

    abstract class Database : RoomDatabase() {
      abstract fun dataDao(): DataDAO
    }

update in version 2, with some table removed and added some new tyable

    @Database(entities = [
      Entity::class,
      //    ArticleEntity::class,
      //    VideoEntity::class,
      //    ImageEntity::class,
      ItemEntity::class,
      TimestampEntity::class
    ], version = 2, exportSchema = true)
    abstract class Database : RoomDatabase() {
      abstract fun dataDao(): DataDAO
    }

it is using `fallbackToDestructiveMigration()` to create the database:

    fun initDatabase(context: Context) {
        val database = Room.databaseBuilder(context, Database::class.java, "myDatabase")
            .fallbackToDestructiveMigration()
            .build()

        dataDao = database.dataDao()
    }

but when install the updated build,  it got error at run:

```java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.```

although the version number has been increased.

The data in the old table are not needed, but to force uninstall the app or clear app's data first are not a accepted solution for the app running in the field.

**How to make the upgrade without have to uninstall the app?**

looking at the Room code

    private void checkIdentity(SupportSQLiteDatabase db) {
        String identityHash = null;
        if (hasRoomMasterTable(db)) {
            Cursor cursor = db.query(new SimpleSQLiteQuery(RoomMasterTable.READ_QUERY));
            //noinspection TryFinallyCanBeTryWithResources
            try {
                if (cursor.moveToFirst()) {
                    identityHash = cursor.getString(0);
                }
            } finally {
                cursor.close();
            }
        }
        if (!mIdentityHash.equals(identityHash) && !mLegacyHash.equals(identityHash)) {
            throw new IllegalStateException("Room cannot verify the data integrity. Looks like"
                    + " you've changed schema but forgot to update the version number. You can"
                    + " simply fix this by increasing the version number.");
        }
    }

    private static boolean hasRoomMasterTable(SupportSQLiteDatabase db) {
        Cursor cursor = db.query("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name='"
                + RoomMasterTable.TABLE_NAME + "'");
        //noinspection TryFinallyCanBeTryWithResources
        try {
            return cursor.moveToFirst() && cursor.getInt(0) != 0;
        } finally {
            cursor.close();
        }
    }

So if the old database exist 'RoomMasterTable.TABLE_NAME' it will have a different hash then the `mIdentityHash` and t got the exception.

Since this is a upgrade the app should already have the 'RoomMasterTable.TABLE_NAME',  how would the `fallbackToDestructiveMigration()`  help?

**Comment by lannyf77** [comment]
seems it does not get `java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.` . But on some os version the old table are still kept with old data.

**Comment by andrew-nemtsev** [comment]
I have the same issue with java.lang.IllegalStateException exception after schema version update even if .fallbackToDestructiveMigration() method is called:

`private fun buildDatabase(context: Context) = Room.databaseBuilder(context.applicationContext,
            ApplicationDb::class.java, "app.db")
            .fallbackToDestructiveMigration()
            .build()`

Stacktrace is:

`java.lang.IllegalStateException: A migration from 2 to 3 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
        at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:117)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:124)`
