### ISSUE TITLE
kotlin room TypeConverters

### ISSUE THREAD

**Issue by Caij** [googlesamples/android-architecture-components#706]
@Entity
data class Account(@PrimaryKey val uid: Long,
                    val gsidExpired: Boolean,
                    val gsid: String,
                    val screenName: String,
                    val avatar: String,
                   @TypeConverters(OauthConvert::class)
var oauth: WeiCoLoginResponse.Oauth? = null,
@TypeConverters(CookieConvert::class)
var cookie: Cookie? = null)

build error:
/Users/caijing/StudioProjects/seegithub/idol/build/tmp/kapt3/stubs/debug/com/caij/idol/db/Account.java:18: 错误: Cannot figure out how to save this field into database. You can consider adding a type converter for it.
    private com.caij.see.bean.response.WeiCoLoginResponse.Oauth oauth;
                                                                ^
-------------------------------------
@Entity
data class Account(@PrimaryKey val uid: Long,
                    val gsidExpired: Boolean,
                    val gsid: String,
                    val screenName: String,
                    val avatar: String
) {
    @TypeConverters(OauthConvert::class)
    var oauth: WeiCoLoginResponse.Oauth? = null
    @TypeConverters(CookieConvert::class)
    var cookie: Cookie? = null
}

build success 

how to use TypeConverters annotation on kotlin data object constructor

**Comment by windows7lake** [comment]
```kotlin
@Entity(tableName = "user_repos")
@TypeConverters(ReposPersistentConverter::class)
data class Repo(
        @PrimaryKey
        val id: Long,
     
        val owner: RepoOwner,
)


class ReposPersistentConverter {
    // RepoOwner
    @TypeConverter
    fun storeRepoOwnerToString(data: RepoOwner): String = data.toJson()

    @TypeConverter
    fun storeStringToRepoOwner(value: String): RepoOwner = value.fromJson()
}
```
you can try this

**Comment by Caij** [comment]
thanks
