### ISSUE TITLE
Why use  `result.addSource(dbSource, newData -> result.setValue(Resource.success(newData)));`, instead of  `result.setValue(Resource.success(data));`?

### ISSUE THREAD

**Issue by chenycu** [googlesamples/android-architecture-components#71]
https://github.com/googlesamples/android-architecture-components/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/repository/NetworkBoundResource.java#L53
Why use 
`result.addSource(dbSource, newData -> result.setValue(Resource.success(newData)));`,
instead of 
`result.setValue(Resource.success(data));`?

**Comment by yigit** [comment]
Assigning it as a source means that if the `LiveData` received from database changes, the value will be updated. If we called `setValue`, it would miss future changes that might happen in the database.
