### ISSUE TITLE
liveData with Coroutines

### ISSUE THREAD

**Issue by isfaaghyth** [googlesamples/android-architecture-components#715]
Hi! who already use for this one `androidx.lifecycle:lifecycle-livedata-ktx:2.2.0-alpha01` ? I've tried it into my repository layer but doesn't work (i'm using `retrofit 2.6.0`). this is my code:

```kt
interface Service {
     @GET("/data")
     suspend fun getData(): Data
}
```

```kt
class Repository @Inject constructor(val service: Service) {
     fun getData(): LiveData<Data> = liveData {
          val data = service.getData()
          emit(data)
     }
}
```

and this is my viewmodel:
```kt
...
     fun fetch() {
          viewModelScope.launch {
              val data = repository.getData()
              println(data.value)
          }
     }
...
```

the result is `null`.

any idea about this?
thanks!

**Comment by alexkazancew** [comment]
Hi @isfaaghyth . Your liveData from repository.getData() don`t have active observers. So liveData not emiting data.

**Comment by isfaaghyth** [comment]
so, which a good way for my case? @alexkazancew

**Comment by alexkazancew** [comment]
@isfaaghyth i update my previous answer

**Comment by isfaaghyth** [comment]
it works! thanks @alexkazancew

**Comment by GuilhE** [comment]
How about using` liveData{... emit()} `while using `SavedStateHandle`? Is there any benefit?
Here's my SO [question](https://stackoverflow.com/questions/58079198/livedata-with-coroutines-and-savedstatehandle)

**Comment by alexkazancew** [comment]
@GuilhE I think you can do something like this 
```
class SomeViewModel(private val savedStateHandle: SavedStateHandle) : ViewModel() {

    companion object {
        private const val PAGE_KEY = "page_key"
    }

    private val _page = MutableLiveData<PageId>(savedStateHandle.get(PAGE_KEY))

    private val _itemLiveData = Transformations.switchMap(_page) { pageId -> repository.getNextPage(pageId) }
    val itemLiveData: LiveData<MyItem> = _itemLiveData

    suspend fun nextPage(pageId: PageId) {
        _page.postValue(pageId)
    }

    override fun onCleared() {
        super.onCleared()
        savedStateHandle.set(PAGE_KEY, _page.value)
    }
}
```
Let me know if it helped you.
