### ISSUE TITLE
projection in contentProvider

### ISSUE THREAD

**Issue by wsw22** [googlesamples/android-architecture-components#75]
in PersistenceContentProviderSample, the projection in contentProvider is not used

in MainActivity.java, line 67-70, add projection {Cheese.COLUMN_NAME}
![add projection](https://user-images.githubusercontent.com/22638763/27514614-916f53ba-59c2-11e7-870d-595710fa8f65.png)

in SampleContentProvider.java, line 85-86, query data
![query data](https://user-images.githubusercontent.com/22638763/27514615-98853304-59c2-11e7-8241-1f7202de7cf2.png)

this is selectAll(), in CheeseDao.java, SELECT * 
![select all](https://user-images.githubusercontent.com/22638763/27514617-a3d63492-59c2-11e7-9157-9f02679e1619.png)

the projection is not used, and i add some log
![add log](https://user-images.githubusercontent.com/22638763/27514599-045f7612-59c2-11e7-9042-8cae843e6e24.png)

this is the output
![log](https://user-images.githubusercontent.com/22638763/27514601-12a4a936-59c2-11e7-9546-f8a86ccedf5e.png)

how to use Room in contentProvider with projection, where arguments in contentResolver, contentProvider?

**Comment by yigit** [comment]
Unfortunately, there is no easy way to do it with Room right now. You can always fall back to querying the database directly via `Room#query` but you'll miss the compile time verification.

That is part of the problem w/ the content provider projection API where the projection values are not guaranteed to be columns in the database.

**Comment by davigonz** [comment]
Hi @yigit , is there something new in Room regarding this topic? Thanks
