### ISSUE TITLE
Handling multiple Dagger Components with different scopes

### ISSUE THREAD

**Issue by makaroffandrey** [googlesamples/android-architecture-components#76]
Please advise on how can I extend the approach shown in [GithubBrowserSample](https://github.com/googlesamples/android-architecture-components/tree/master/GithubBrowserSample) to support multiple Dagger Components.
I currently have two components: one with a `@Singleton` scope that is stored for the whole life of the application, and a dependent component scoped `@PerUser`, that gets recreated every time a new user loggs in.
You are currently using a `Map` provided to `DispatchingAndroidInjector` to determine from where each `Activity` gets its dependencies, but I do not see a way to produce such a map from two components automatically using Dagger annotations. Should I create two maps and a new subclass of `AndroidInjector` to handle them?
Also, I see that `@ContributesAndroidInjector` is a convenient way to create Dagger components for each `Activity` or `Fragment`. Is there a way to add `@Module`s and `@Scope` to them?

**Comment by yigit** [comment]
Seems like a question for the dagger project.
Please report there: https://github.com/google/dagger
