### ISSUE TITLE
Rxjava 2 with Android Architecture Components library

### ISSUE THREAD

**Issue by shakil807g** [googlesamples/android-architecture-components#80]
I am using rxjava 2 to call api in ViewModel is it the anything wrong with this approach 

    public class CaseDetailViewModel extends AndroidViewModel {

        @Inject
        ApiFactory apiFactory;

    private final MutableLiveData<Resource<List<UserNames>>> usernames;

    public CaseDetailViewModel(Application application) {
        super(application);
        ((MyApplication)application).getAppComponent().inject(this);
        usernames = new MutableLiveData<>();

    }

    public LiveData<Resource<List<UserNames>>> getUserName(String data ,boolean forceUpdate){
        if(usernames.getValue() == null){
            usernames.setValue(Resource.loading(null));
            apiFactory.usersNames("-1")
                    .subscribeOn(Schedulers.io())
                    .subscribe(model -> {
                        if(model.status){
                            usernames.postValue(Resource.success(model.data));
                        }else {
                            usernames.postValue(Resource.error(model.getMessage(),null));
                        }

                    }, Throwable::printStackTrace);

        }
        return usernames;
        }
     }

**Comment by listenzz** [comment]
May be pure rxjava is better. see https://github.com/listenzz/RxCommand

**Comment by JoseAlcerreca** [comment]
Since this is not related to the samples, closing for now.
