### ISSUE TITLE
Cannot compile project with libraries in my own Maven repository under a Proxy

### ISSUE THREAD

**Issue by manuelvicnt** [googlesamples/android-architecture-components#81]
I'm trying to use Room importing the libraries into my own Maven repository which is under a proxy. 

```
    def room_version = "1.0.0-alpha3"
    compile "android.arch.persistence.room:runtime:$room_version"
    kapt "android.arch.persistence.room:compiler:$room_version"
```

When compiling and syncing the project I get this error:

```
Error:Could not find common.jar (android.arch.persistence.room:common:1.0.0-alpha3).
Searched in the following locations:
    https://my_own_maven_repo/android/arch/persistence/room/common/1.0.0-alpha3/common-1.0.0-alpha3.jar
```

The file exists in my repository, I'm able to access it locally. Is it trying to go to a different place/repository every time it tries to compile the project? It works if I add the Google maven repo in the `build.gradle` file but I want to avoid it.

Thank you

**Comment by JoseAlcerreca** [comment]
Doesn't seem to be related to the components or to the samples. I suggest you try to file a bug against the tools team. Closing for now.
