### ISSUE TITLE
Room Inconsistency

### ISSUE THREAD

**Issue by shanno29** [googlesamples/android-architecture-components#86]
It would be more helpful for @Insert and @Delete to return a Long Object or the object inserted / deleted instead of a primitive. This way all methods would be able to return either a LiveData or Observable wrapped object.

**Comment by trubitsyn** [comment]
Tried to do this a couple of minutes before and became disappointed it's impossible. I think it would be extremely helpful if everything returned observables.

**Comment by mynote** [comment]
If the @Insert method receives only 1 parameter, it can return a long, which is the new rowId for the inserted item. If the parameter is an array or a collection, it should return long[] or List<Long> instead.

**Comment by florina-muntenescu** [comment]
Not a sample issue. Closing this.
Architecture components issues or feature requests should be done via the [issue tracker](https://developers.google.com/issue-tracker/).
