### ISSUE TITLE
[Question] How to represent nested One to Many Relationship using Repository pattern in GithubBrowserSample

### ISSUE THREAD

**Issue by OmkarAmberkar** [googlesamples/android-architecture-components#92]
First of all I want to say thanks for these samples which enlighten working with these new components significantly, looking at the code there is a lot to learn.

While playing with GithubBrowserSample project, I noticed that if my POJO have nested One to Many Relationships like this:-

```
public class User {
  public int id;
  public List<Pet> pets;
}

public class Pet {
  public int id;
  public String petName;
  public List<Category> categories;
}

public class Category {
  public int id;
  public String categoryName;
}
```

Or if Pet class is @Embedded into the User class and has a list of Category like this

```
public class User {
  public int id;
  public Pet pet;
}

public class Pet {
  public int id;
  public String petName;
  public List<Category> categories;
}

public class Category {
  public int id;
  public String categoryName;
}
```
It becomes really difficult to persisting and querying data having this kind of data structure with repository architecture demonstrated in GithubBrowserSample. I can use a @TypeConverter to convert  the list of objects to string and vice versa,  but would that be a recommended way? If not,  how would you recommend it to be done? Can you provide some additional example or information about persisting this kind of data structure with room using the repository pattern similar to GithubBrowserSample.

**Comment by GitHubMurt** [comment]
Please answer for that. On internet is no really solution for that. How to handle relations with list of entities. I'm curious if you haven't predict this standard functionality or you don't see the problem, that many programmes are struggle with nowadays

**Comment by nguyengialeit** [comment]
I have same question, still waiting for answer....

**Comment by nicolasjafelle** [comment]
I had the same scenario and what I did was to use gson and TypeConverts to convert to Json String and reconvert to my Object class. `@embedded` seems to flat the nested object and add all the attributes in the same table which si nice but if you have 5 objects you will have 1 table composed with 5 objects, does make sense? For that purpose I can easily convert all my nested objects into Json String and simple use one table one column with all the flatten representation in a Json String...

**Comment by contrudar** [comment]
@florina-muntenescu @JoseAlcerreca hello guys, can you please answer this question. Nested collections are really common case and to know how to query them using Room is very necessary. I created a question on [stackoverflow](https://stackoverflow.com/questions/48172364/how-to-query-a-complex-nested-objects-in-android-room) and if you could answer it, it would be great. At least, give the idea how to handle such cases using Room. Thanks in advance.

**Comment by florina-muntenescu** [comment]
I wrote about simplifying one-to-many queries via `@Relation`, [here](https://medium.com/google-developers/7-pro-tips-for-room-fbadea4bfbd1) - tip 6.

**Comment by dhaag23** [comment]
I'd love to see a fully working sample, particularly one using `@Relation` instead of just some code snippets. That would simplify things tremendously.

**Comment by aakashbhusal7** [comment]
any solution to this guys? I am still stuck on it

**Comment by mochadwi** [comment]
ping

**Comment by farruhha** [comment]
> I wrote about simplifying one-to-many queries via `@Relation`, [here](https://medium.com/google-developers/7-pro-tips-for-room-fbadea4bfbd1) - tip 6.

It is the same example over and over again online. Is it possible to implement remove and insert with relation object, e.g in your example for users and pets relation.

**Comment by farruhha** [comment]
I am still stuck on this. And after struggling with Room, I have decided to come back to SQlite world. Room is still pre-mature, and only works for super simple projects. It is not pretty flexible. And it is ORM, is not it? Haha.

**Comment by mwshubham** [comment]
There is no need to dislike the @florina-muntenescu comment. You just need to put more effort. Follow https://medium.com/androiddevelopers/database-relations-with-room-544ab95e4542#:~:text=An%20important%20part%20of%20designing,with%20one%20annotation%3A%20%40Relation%20. In order to achieve relation child and check this gist https://gist.github.com/mwshubham/8bb42465b7bf3efb1567558631ea12f0

You need to map the DB -> Remote and Remote -> DB vice versa as per need. Since we serve data from DB we need to map the data into single object using Mapper.

I will make my sample public in one or two days (WIP).

**Comment by gurpreetsudan** [comment]
I have a similar problem where I have an embedded object inside others and then a list inside the second one? anyone figured it out ??? I don't want to use GSON or Moshi to flat it as it will slow down and I won't be able to query the tables separately

**Comment by mwshubham** [comment]
Check my one to many relationship in a sample project. https://github.com/mwshubham/TheGoodParts/blob/master/app/src/main/java/app/thegoodparts/data/source/remote/response/CompanyMemberRelation.kt   
Refer to https://github.com/mwshubham/TheGoodParts/tree/master/app/src/main/java/app/thegoodparts/ui/fragments/companylist for usage

**Comment by tunjid** [comment]
Many to many relationships can be seen in the Now In Android Sample app: https://github.com/android/nowinandroid/blob/main/core/database/src/main/java/com/google/samples/apps/nowinandroid/core/database/model/PopulatedNewsResource.kt
