### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhoujingheng** [googlesamples/android-architecture-components#96]
Error:Failed to resolve: android.arch.core:core-testing:1.0.0-alpha1

Error:Failed to resolve: android.arch.lifecycle:extensions:1.0.0-alpha1

Error:Failed to resolve: annotationProcessor

Error:Failed to resolve: android.arch.persistence.room:runtime:1.0.0-alpha1

Error:Failed to resolve: android.arch.lifecycle:runtime:1.0.0-alpha1

**Comment by jimandreas** [comment]
Be sure to add maven as a repository:

https://developer.android.com/topic/libraries/architecture/adding-components.html

**Comment by zhoujingheng** [comment]
都是有导入的

**Comment by zhoujingheng** [comment]
have import

**Comment by jimandreas** [comment]
See this issue for discussion: https://github.com/googlesamples/android-architecture-components/issues/4

Developers using VPN have reported difficulty connecting to :  maven.google.com
It is not clear to me what the best solution might be.   Check the issue link for clues.
